-- 100Lights baseline schema
--
-- GENERATED by scripts/db/extract-schema.mjs from the DDL the application
-- executed at runtime. Do not hand-edit; add a new numbered migration instead.
--
-- Extensions: 1   Tables: 72   Indexes: 36   Alters: 46
-- Statements needing manual review (contain ${} interpolation): 0

-- ──────────────────────────────────────────────────────────────────────────
-- Extensions (1) — must precede tables using their types
-- ──────────────────────────────────────────────────────────────────────────

-- from lib/track-embeddings.ts
CREATE EXTENSION IF NOT EXISTS vector;

-- ──────────────────────────────────────────────────────────────────────────
-- Tables (72)
-- ──────────────────────────────────────────────────────────────────────────

-- from app/api/admin/users/[userId]/route.ts
CREATE TABLE IF NOT EXISTS user_notes (user_id TEXT PRIMARY KEY, note TEXT NOT NULL DEFAULT '', tags JSONB, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

-- from app/api/app-history/route.ts
CREATE TABLE IF NOT EXISTS app_history (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL,
    app_slug   TEXT NOT NULL,
    title      TEXT NOT NULL,
    subtitle   TEXT,
    data       JSONB,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from app/api/community/[id]/audio/route.ts
CREATE TABLE IF NOT EXISTS community_stream_log (
    item_id UUID NOT NULL,
    day DATE NOT NULL,
    count INT NOT NULL DEFAULT 0,
    PRIMARY KEY (item_id, day)
  );

-- from app/api/community/[id]/route.ts
CREATE TABLE IF NOT EXISTS community_action_log (
    user_id TEXT NOT NULL,
    at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from app/api/feedback/route.ts
CREATE TABLE IF NOT EXISTS feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT,
    email TEXT,
    message TEXT NOT NULL,
    page TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from app/api/folders/route.ts
CREATE TABLE IF NOT EXISTS folders (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from app/api/library/items/route.ts
CREATE TABLE IF NOT EXISTS user_library_items (
    id         TEXT NOT NULL,
    user_id    TEXT NOT NULL,
    type       TEXT NOT NULL,
    name       TEXT NOT NULL DEFAULT '',
    data       JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, id)
  );

-- from app/api/library/route.ts
CREATE TABLE IF NOT EXISTS user_sounds (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL,
    name         TEXT NOT NULL,
    category     TEXT NOT NULL DEFAULT 'custom',
    r2_key       TEXT NOT NULL,
    duration     DOUBLE PRECISION NOT NULL DEFAULT 0,
    content_type TEXT NOT NULL DEFAULT '',
    folder       TEXT,
    parent_folder TEXT,
    tags         JSONB,
    musical_key  TEXT,
    bpm          DOUBLE PRECISION,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from app/api/media/presign-upload/route.ts
CREATE TABLE IF NOT EXISTS upload_log (
    user_id TEXT NOT NULL,
    key TEXT NOT NULL,
    size BIGINT NOT NULL DEFAULT 0,
    at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from app/api/modules/confirm/route.ts
CREATE TABLE IF NOT EXISTS module_licenses (
    user_id TEXT NOT NULL,
    module_key TEXT NOT NULL,
    license_type TEXT NOT NULL CHECK (license_type IN ('free', 'purchased', 'bundle')),
    purchased_at TIMESTAMPTZ DEFAULT NOW(),
    stripe_payment_intent_id TEXT,
    PRIMARY KEY (user_id, module_key)
  );

-- from app/api/podcast/[id]/publish/route.ts
CREATE TABLE IF NOT EXISTS podcast_feeds (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL,
    project_id  TEXT NOT NULL UNIQUE,
    slug        TEXT NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
  );

-- from app/api/projects/[id]/versions/route.ts
CREATE TABLE IF NOT EXISTS project_versions (
    id          TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL,
    name        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    data        JSONB NOT NULL
  );

-- from app/api/scenes/route.ts
CREATE TABLE IF NOT EXISTS user_scenes (
    user_id    TEXT NOT NULL,
    id         TEXT NOT NULL,
    name       TEXT NOT NULL,
    data       JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, id)
  );

-- from app/api/settings/route.ts
CREATE TABLE IF NOT EXISTS user_settings (
    user_id    TEXT        PRIMARY KEY,
    data       JSONB       NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/admin-audit.ts
CREATE TABLE IF NOT EXISTS admin_audit (
    id         BIGSERIAL PRIMARY KEY,
    actor      TEXT        NOT NULL DEFAULT 'admin',  -- admin email when known
    action     TEXT        NOT NULL,                  -- e.g. 'gift.grant', 'article.purge'
    target     TEXT,                                  -- the thing acted on (userId, slug, code…)
    detail     JSONB,                                 -- action-specific payload
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/affiliates.ts
CREATE TABLE IF NOT EXISTS affiliates (
    code              TEXT        PRIMARY KEY,
    name              TEXT        NOT NULL,
    contact           TEXT,
    commission_pct    NUMERIC     NOT NULL DEFAULT 20,
    commission_months INTEGER,
    perk_days         INTEGER     NOT NULL DEFAULT 14,
    active            BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/affiliates.ts
CREATE TABLE IF NOT EXISTS affiliate_applications (
    id          BIGSERIAL   PRIMARY KEY,
    name        TEXT        NOT NULL,
    contact     TEXT        NOT NULL,
    platform    TEXT,
    audience    TEXT,
    links       TEXT,
    note        TEXT,
    status      TEXT        NOT NULL DEFAULT 'pending',
    code        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/affiliates.ts
CREATE TABLE IF NOT EXISTS affiliate_commissions (
    id                BIGSERIAL   PRIMARY KEY,
    code              TEXT        NOT NULL,
    user_id           TEXT        NOT NULL,
    stripe_invoice_id TEXT        NOT NULL UNIQUE,
    invoice_cents     INTEGER     NOT NULL,
    commission_cents  INTEGER     NOT NULL,
    currency          TEXT        NOT NULL DEFAULT 'usd',
    invoice_at        TIMESTAMPTZ NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/affiliates.ts
CREATE TABLE IF NOT EXISTS affiliate_payouts (
    id          BIGSERIAL   PRIMARY KEY,
    code        TEXT        NOT NULL,
    amount_cents INTEGER    NOT NULL,
    method      TEXT,
    note        TEXT,
    paid_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/age-gate.ts
CREATE TABLE IF NOT EXISTS user_age (
    user_id      TEXT        PRIMARY KEY,
    birthdate    DATE        NOT NULL,
    blocked      BOOLEAN     NOT NULL DEFAULT FALSE,
    confirmed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/ai-cache.ts
CREATE TABLE IF NOT EXISTS ai_cache (
    hash        TEXT PRIMARY KEY,
    kind        TEXT NOT NULL,
    result      JSONB NOT NULL,
    hits        INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_hit_at TIMESTAMPTZ
  );

-- from lib/announcements.ts
CREATE TABLE IF NOT EXISTS announcements (
  id BIGSERIAL PRIMARY KEY,
  message TEXT NOT NULL,
  level TEXT NOT NULL DEFAULT 'info',
  href TEXT,
  href_label TEXT,
  audience TEXT NOT NULL DEFAULT 'all',
  dismissible BOOLEAN NOT NULL DEFAULT true,
  active BOOLEAN NOT NULL DEFAULT true,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/api-usage.ts
CREATE TABLE IF NOT EXISTS api_usage (
    id            TEXT PRIMARY KEY,
    user_id       TEXT,                       -- null = local/script usage
    provider      TEXT NOT NULL,              -- 'elevenlabs' | 'anthropic' | 'deepgram' | 'replicate' | 'openai' | ...
    operation     TEXT,                       -- 'music-gen' | 'stem-sep' | 'vision' | 'transcribe' | 'image' | 'article' | ...
    units         REAL,                       -- amount consumed
    unit_type     TEXT,                       -- 'credits' | 'tokens' | 'seconds' | 'characters' | 'predictions'
    input_tokens  INTEGER,                    -- LLM breakdown (optional)
    output_tokens INTEGER,
    cost_usd      REAL,                        -- optional estimate
    metadata      JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/app-targets.ts
CREATE TABLE IF NOT EXISTS sound_targets (
    id           TEXT PRIMARY KEY,
    label        TEXT NOT NULL,
    category     TEXT NOT NULL DEFAULT 'app',
    description  TEXT NOT NULL DEFAULT '',
    r2_key       TEXT,
    content_type TEXT NOT NULL DEFAULT '',
    duration     DOUBLE PRECISION,
    tags         TEXT[] NOT NULL DEFAULT '{}',
    app_slug     TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/broadcast-control.ts
CREATE TABLE IF NOT EXISTS broadcast_agents (
    worker_id TEXT PRIMARY KEY,
    capacity  INT NOT NULL DEFAULT 1,
    note      TEXT NOT NULL DEFAULT '',
    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/broadcast-control.ts
CREATE TABLE IF NOT EXISTS broadcast_status (
    slug       TEXT PRIMARY KEY,
    worker_id  TEXT,
    status     TEXT NOT NULL DEFAULT 'offline',
    fps        REAL,
    error      TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/broadcast-stations.ts
CREATE TABLE IF NOT EXISTS broadcast_stations (
    slug       TEXT PRIMARY KEY,
    config     JSONB NOT NULL,        -- { title, tagline, scene, tracks?, jamendo?, shuffle?, showNowPlaying? }
    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    sort       INT NOT NULL DEFAULT 0,
    edited     BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/catalog.ts
CREATE TABLE IF NOT EXISTS catalog_sounds (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    category      TEXT NOT NULL DEFAULT 'custom',
    r2_key        TEXT NOT NULL,
    duration      DOUBLE PRECISION NOT NULL DEFAULT 0,
    content_type  TEXT NOT NULL DEFAULT '',
    folder        TEXT,
    parent_folder TEXT DEFAULT '100Lights Catalog',
    tags          JSONB,
    musical_key   TEXT,
    bpm           DOUBLE PRECISION,
    sort          INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/codes.ts
CREATE TABLE IF NOT EXISTS redemption_codes (
    code            TEXT        PRIMARY KEY,
    kind            TEXT        NOT NULL DEFAULT 'promo',
    grant_days      INTEGER     NOT NULL,
    active          BOOLEAN     NOT NULL DEFAULT TRUE,
    expires_at      TIMESTAMPTZ,
    max_redemptions INTEGER,
    redeemed_count  INTEGER     NOT NULL DEFAULT 0,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/codes.ts
CREATE TABLE IF NOT EXISTS code_redemptions (
    code        TEXT        NOT NULL,
    user_id     TEXT        NOT NULL,
    kind        TEXT        NOT NULL,
    grant_days  INTEGER     NOT NULL,
    grant_until TIMESTAMPTZ NOT NULL,
    redeemed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (code, user_id)
  );

-- from lib/community-server.ts
CREATE TABLE IF NOT EXISTS community_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    author_name TEXT NOT NULL DEFAULT 'Anonymous',
    kind TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    payload JSONB,
    r2_key TEXT,
    votes INT NOT NULL DEFAULT 0,
    downloads INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/community-server.ts
CREATE TABLE IF NOT EXISTS community_votes (
    item_id UUID NOT NULL,
    user_id TEXT NOT NULL,
    PRIMARY KEY (item_id, user_id)
  );

-- from lib/community-server.ts
CREATE TABLE IF NOT EXISTS community_reactions (
    item_id UUID NOT NULL,
    user_id TEXT NOT NULL,
    emoji TEXT NOT NULL,
    PRIMARY KEY (item_id, user_id, emoji)
  );

-- from lib/community-server.ts
CREATE TABLE IF NOT EXISTS community_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id UUID NOT NULL,
    user_id TEXT NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (item_id, user_id)
  );

-- from lib/community-server.ts
CREATE TABLE IF NOT EXISTS community_comments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id UUID NOT NULL,
    user_id TEXT NOT NULL,
    author_name TEXT NOT NULL DEFAULT 'Anonymous',
    body TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/community-server.ts
CREATE TABLE IF NOT EXISTS community_comment_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    comment_id UUID NOT NULL,
    item_id UUID NOT NULL,
    user_id TEXT NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (comment_id, user_id)
  );

-- from lib/community-server.ts
CREATE TABLE IF NOT EXISTS community_collections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    author_name TEXT NOT NULL DEFAULT 'Anonymous',
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ
  );

-- from lib/community-server.ts
CREATE TABLE IF NOT EXISTS community_collection_items (
    collection_id UUID NOT NULL,
    item_id UUID NOT NULL,
    position INT NOT NULL DEFAULT 0,
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (collection_id, item_id)
  );

-- from lib/content/store.ts
CREATE TABLE IF NOT EXISTS content_posts (
    id           TEXT        PRIMARY KEY,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    project_id   TEXT,
    slug         TEXT        NOT NULL DEFAULT 'song-video',
    format       TEXT        NOT NULL DEFAULT 'falling-notes',
    title        TEXT        NOT NULL DEFAULT '',
    caption      TEXT        NOT NULL DEFAULT '',
    platforms    JSONB       NOT NULL DEFAULT '["youtube"]',
    video_key    TEXT        NOT NULL,
    video_type   TEXT        NOT NULL DEFAULT 'video/webm',
    musical      JSONB,
    status       TEXT        NOT NULL DEFAULT 'draft',
    results      JSONB       NOT NULL DEFAULT '{}',
    error        TEXT,
    published_at TIMESTAMPTZ
  );

-- from lib/content-licenses.ts
CREATE TABLE IF NOT EXISTS content_licenses (
    id         BIGSERIAL   PRIMARY KEY,
    name       TEXT        NOT NULL,
    category   TEXT        NOT NULL DEFAULT 'sound',
    source     TEXT,
    license    TEXT,
    url        TEXT,
    notes      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/content-metrics.ts
CREATE TABLE IF NOT EXISTS content_perf (
    id                TEXT PRIMARY KEY,          -- platform video id, or any stable key
    platform          TEXT NOT NULL DEFAULT 'youtube',
    format_tag        TEXT,                      -- lib/content-formats CONTENT_FORMATS.id
    hook_type         TEXT,                      -- lib/content-formats HOOK_TYPES
    title             TEXT,
    length_s          REAL,
    posted_at         TIMESTAMPTZ,
    views             BIGINT DEFAULT 0,
    avg_pct_viewed    REAL,                      -- completion % (the king metric)
    first3s_retention REAL,                      -- % still watching at 3s
    avg_view_s        REAL,                      -- average view duration (seconds)
    likes             INTEGER DEFAULT 0,
    comments          INTEGER DEFAULT 0,
    shares            INTEGER DEFAULT 0,
    subs_gained       INTEGER DEFAULT 0,
    notes             TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/credits.ts
CREATE TABLE IF NOT EXISTS user_credits (
    user_id              TEXT PRIMARY KEY,
    balance              INTEGER NOT NULL DEFAULT 0,
    monthly_grant        INTEGER NOT NULL DEFAULT 0,
    cycle_start          TIMESTAMPTZ,
    free_transcribe_used INTEGER NOT NULL DEFAULT 0,
    free_cycle_start     TIMESTAMPTZ,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/credits.ts
CREATE TABLE IF NOT EXISTS credit_ledger (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL,
    delta      INTEGER NOT NULL,
    reason     TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/credits.ts
CREATE TABLE IF NOT EXISTS credit_grants (
    grant_key  TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/daw-recipes.ts
CREATE TABLE IF NOT EXISTS daw_recipes (
    id            TEXT PRIMARY KEY,
    status        TEXT NOT NULL DEFAULT 'candidate',   -- 'candidate' | 'integrated'
    title         TEXT NOT NULL,
    tagline       TEXT NOT NULL DEFAULT '',
    annotation    JSONB NOT NULL DEFAULT '[]'::jsonb,
    genre         TEXT,
    spec          JSONB NOT NULL,                      -- PracticeRecipe.build() output
    source        TEXT,                                -- where the pattern came from (admin note; not shown to users)
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    integrated_at TIMESTAMPTZ
  );

-- from lib/demo-audio-store.ts
CREATE TABLE IF NOT EXISTS demo_audio_overrides (
    clip         TEXT PRIMARY KEY,
    content_type TEXT NOT NULL,
    data_b64     TEXT NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/dmca.ts
CREATE TABLE IF NOT EXISTS dmca_notices (
    id               BIGSERIAL   PRIMARY KEY,
    complainant_name TEXT        NOT NULL,
    email            TEXT        NOT NULL,
    work_description TEXT        NOT NULL,
    infringing_url   TEXT        NOT NULL,
    signature        TEXT        NOT NULL,
    good_faith       BOOLEAN     NOT NULL DEFAULT FALSE,
    accuracy         BOOLEAN     NOT NULL DEFAULT FALSE,
    status           TEXT        NOT NULL DEFAULT 'open',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/email.ts
CREATE TABLE IF NOT EXISTS email_suppressions (email TEXT PRIMARY KEY, reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

-- from lib/generation-capture.ts
CREATE TABLE IF NOT EXISTS generation_captures (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL,
    prompt       TEXT,
    params       JSONB,
    model        TEXT,
    stem_keys    JSONB,          -- [{ name, key }] in R2
    mix_key      TEXT,
    status       TEXT NOT NULL DEFAULT 'pending',   -- pending | processed | failed
    error        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ
  );

-- from lib/guest-sessions.ts
CREATE TABLE IF NOT EXISTS guest_sessions (
    token              TEXT PRIMARY KEY,
    project_id         TEXT NOT NULL,
    host_user_id       TEXT NOT NULL,
    guest_name         TEXT,
    status             TEXT NOT NULL DEFAULT 'pending',
    r2_key             TEXT,
    session_start_ms   BIGINT,
    recording_start_ms BIGINT,
    timeline_offset_ms BIGINT,
    duration_ms        BIGINT,
    created_at         TIMESTAMPTZ DEFAULT NOW()
  );

-- from lib/learn-paths-store.ts
CREATE TABLE IF NOT EXISTS learn_paths (
    slug          TEXT        PRIMARY KEY,
    title         TEXT        NOT NULL,
    goal          TEXT        NOT NULL DEFAULT '',
    description   TEXT        NOT NULL DEFAULT '',
    emoji         TEXT        NOT NULL DEFAULT '📚',
    level         TEXT        NOT NULL DEFAULT 'beginner',
    article_slugs JSONB       NOT NULL DEFAULT '[]',
    sort_order    INTEGER,
    active        BOOLEAN     NOT NULL DEFAULT TRUE,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/learn-schema.ts
CREATE TABLE IF NOT EXISTS learn_articles (
    slug        TEXT PRIMARY KEY,
    title       TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    date        TEXT NOT NULL,
    updated     TEXT,
    tags        TEXT NOT NULL DEFAULT '',
    draft       BOOLEAN NOT NULL DEFAULT true,
    body        TEXT NOT NULL DEFAULT ''
  );

-- from lib/learn-schema.ts
CREATE TABLE IF NOT EXISTS learn_reactions (
    slug TEXT PRIMARY KEY,
    yes  INTEGER NOT NULL DEFAULT 0,
    no   INTEGER NOT NULL DEFAULT 0
  );

-- from lib/learn-schema.ts
CREATE TABLE IF NOT EXISTS article_todo (
    slug    TEXT PRIMARY KEY,
    note    TEXT NOT NULL DEFAULT '',
    updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/notifications-server.ts
CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    type TEXT NOT NULL,
    item_id UUID,
    actor_name TEXT NOT NULL DEFAULT '',
    body TEXT NOT NULL DEFAULT '',
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/pexels-bg.ts
CREATE TABLE IF NOT EXISTS pexels_bg (
    id         TEXT PRIMARY KEY,
    pexels_id  BIGINT UNIQUE NOT NULL,
    title      TEXT NOT NULL DEFAULT '',
    mp4        TEXT NOT NULL,
    poster     TEXT NOT NULL DEFAULT '',
    width      INT NOT NULL DEFAULT 0,
    height     INT NOT NULL DEFAULT 0,
    duration   INT NOT NULL DEFAULT 0,
    category   TEXT NOT NULL DEFAULT 'Abstract',
    brightness TEXT NOT NULL DEFAULT 'mid',
    speed      TEXT NOT NULL DEFAULT 'standard',
    tags       TEXT[] NOT NULL DEFAULT '{}',
    author     TEXT NOT NULL DEFAULT '',
    author_url TEXT NOT NULL DEFAULT '',
    status     TEXT NOT NULL DEFAULT 'active',
    block_edits TEXT[] NOT NULL DEFAULT '{}',
    added_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/platform-flags.ts
CREATE TABLE IF NOT EXISTS platform_config (
    key        TEXT PRIMARY KEY,
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/project-access.ts
CREATE TABLE IF NOT EXISTS project_members (
    project_id UUID NOT NULL,
    email TEXT NOT NULL,
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (project_id, email)
  );

-- from lib/project-access.ts
CREATE TABLE IF NOT EXISTS project_suggestions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL,
    author_id TEXT NOT NULL,
    author_name TEXT NOT NULL DEFAULT 'A collaborator',
    note TEXT NOT NULL DEFAULT '',
    data JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/radio-mirror.ts
CREATE TABLE IF NOT EXISTS radio_audio_mirror (
    src_url    TEXT PRIMARY KEY,
    r2_url     TEXT NOT NULL,
    r2_key     TEXT NOT NULL,
    bytes      BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/reading-progress.ts
CREATE TABLE IF NOT EXISTS article_reads (
    user_id  TEXT        NOT NULL,
    slug     TEXT        NOT NULL,
    read_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, slug)
  );

-- from lib/saved-segments.ts
CREATE TABLE IF NOT EXISTS saved_segments (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  criteria JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/stt-corrections.ts
CREATE TABLE IF NOT EXISTS stt_corrections (
    id          TEXT PRIMARY KEY,
    source      TEXT NOT NULL DEFAULT 'captions',   -- 'captions' | 'video'
    original    TEXT NOT NULL,                       -- what the local model transcribed
    final       TEXT NOT NULL,                       -- what the user confirmed/corrected it to
    corrected   BOOLEAN NOT NULL,                    -- final != original
    confidence  REAL,                                -- the hybrid's confidence on this caption
    start_sec   REAL,
    end_sec     REAL,
    user_id     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/track-embeddings.ts
CREATE TABLE IF NOT EXISTS track_embeddings (
    id        TEXT PRIMARY KEY,
    title     TEXT NOT NULL DEFAULT '',
    artist    TEXT NOT NULL DEFAULT '',
    audio     TEXT NOT NULL,
    tags      TEXT[] NOT NULL DEFAULT '{}',
    source    TEXT NOT NULL DEFAULT 'jamendo',
    license   TEXT NOT NULL DEFAULT '',
    embedding vector(512),
    added_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/user-crm.ts
CREATE TABLE IF NOT EXISTS user_note_entries (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  body TEXT NOT NULL,
  author TEXT NOT NULL DEFAULT 'admin',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/user-crm.ts
CREATE TABLE IF NOT EXISTS user_tasks (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  body TEXT NOT NULL,
  due_at TIMESTAMPTZ,
  done_at TIMESTAMPTZ,
  author TEXT NOT NULL DEFAULT 'admin',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/user-prefs.ts
CREATE TABLE IF NOT EXISTS user_prefs (
    user_id           TEXT PRIMARY KEY,
    ai_corpus_opt_out BOOLEAN NOT NULL DEFAULT false,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/voice-corrections-db.ts
CREATE TABLE IF NOT EXISTS voice_corrections (
    id          TEXT PRIMARY KEY,
    ts          BIGINT NOT NULL DEFAULT 0,
    app_version TEXT NOT NULL DEFAULT '',
    detected    JSONB NOT NULL DEFAULT '[]'::jsonb,
    corrected   JSONB NOT NULL DEFAULT '[]'::jsonb,
    diff        JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence    JSONB NOT NULL DEFAULT '{}'::jsonb,
    r2_key      TEXT,
    audio_sr    DOUBLE PRECISION,
    audio_dur   DOUBLE PRECISION,
    settings    JSONB NOT NULL DEFAULT '{}'::jsonb,
    comment     TEXT NOT NULL DEFAULT '',
    status      TEXT NOT NULL DEFAULT 'new',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

-- from lib/webhook-log.ts
CREATE TABLE IF NOT EXISTS webhook_events (
  id BIGSERIAL PRIMARY KEY,
  source TEXT NOT NULL,
  event_type TEXT NOT NULL,
  event_id TEXT,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'received',
  error TEXT,
  replay_of BIGINT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  handled_at TIMESTAMPTZ
  );

-- from db/schema.legacy.sql (only definition anywhere)
CREATE TABLE IF NOT EXISTS projects (
  id         TEXT        PRIMARY KEY,
  user_id    TEXT        NOT NULL,
  name       TEXT        NOT NULL,
  saved_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  data       JSONB       NOT NULL,
  deleted_at TIMESTAMPTZ          -- NULL = active; non-null = in trash
);

-- from db/schema.legacy.sql (only definition anywhere)
CREATE TABLE IF NOT EXISTS usage (
  user_id   TEXT        NOT NULL,
  action    TEXT        NOT NULL,
  count     INTEGER     NOT NULL DEFAULT 0,
  reset_at  TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, action)
);

-- from db/schema.legacy.sql (only definition anywhere)
CREATE TABLE IF NOT EXISTS subscriptions (
  user_id            TEXT        PRIMARY KEY,
  stripe_customer_id TEXT        NOT NULL,
  stripe_sub_id      TEXT,
  plan               TEXT        NOT NULL DEFAULT 'free',
  status             TEXT        NOT NULL DEFAULT 'active',
  current_period_end TIMESTAMPTZ,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  gift_plan          TEXT,                 -- admin-gifted plan (e.g. 'pro')
  gift_until         TIMESTAMPTZ           -- NULL = indefinite; past date = expired
);

-- ──────────────────────────────────────────────────────────────────────────
-- Column & constraint changes (46)
-- ──────────────────────────────────────────────────────────────────────────

-- from app/api/feedback/route.ts
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

-- from app/api/folders/route.ts
ALTER TABLE folders ADD COLUMN IF NOT EXISTS parent_id TEXT;

-- from app/api/folders/route.ts
ALTER TABLE folders ADD COLUMN IF NOT EXISTS banner TEXT;

-- from app/api/folders/route.ts
ALTER TABLE folders ADD COLUMN IF NOT EXISTS logo TEXT;

-- from app/api/library/items/route.ts
ALTER TABLE user_library_items DROP CONSTRAINT user_library_items_pkey;

-- from app/api/library/items/route.ts
ALTER TABLE user_library_items ADD PRIMARY KEY (user_id, id);

-- from app/api/projects/[id]/route.ts
ALTER TABLE projects ADD COLUMN IF NOT EXISTS folder_id TEXT;

-- from app/api/projects/route.ts
ALTER TABLE projects ADD COLUMN IF NOT EXISTS slug TEXT;

-- from app/api/projects/route.ts
ALTER TABLE projects ADD COLUMN IF NOT EXISTS owner_username TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS tax_token TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS legal_name TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS business_name TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS tax_address TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS tax_city TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS tax_state TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS tax_zip TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS tax_class TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS tin_last4 TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS tin_enc TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS w9_received_at TIMESTAMPTZ;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS tax_updated_at TIMESTAMPTZ;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS stripe_account_id TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS connect_payouts_enabled BOOLEAN NOT NULL DEFAULT FALSE;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS connect_details_submitted BOOLEAN NOT NULL DEFAULT FALSE;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS connect_requirements TEXT;

-- from lib/affiliates.ts
ALTER TABLE affiliates ADD COLUMN IF NOT EXISTS connect_updated_at TIMESTAMPTZ;

-- from lib/broadcast-control.ts
ALTER TABLE broadcast_stations ADD COLUMN IF NOT EXISTS desired_live BOOLEAN NOT NULL DEFAULT FALSE;

-- from lib/broadcast-stations.ts
ALTER TABLE broadcast_stations ADD COLUMN IF NOT EXISTS edited BOOLEAN NOT NULL DEFAULT FALSE;

-- from lib/community-server.ts
ALTER TABLE community_items ADD COLUMN IF NOT EXISTS removed_at     TIMESTAMPTZ;

-- from lib/community-server.ts
ALTER TABLE community_items ADD COLUMN IF NOT EXISTS removed_by     TEXT;

-- from lib/community-server.ts
ALTER TABLE community_items ADD COLUMN IF NOT EXISTS removed_reason TEXT;

-- from lib/community-server.ts
ALTER TABLE community_items ADD COLUMN IF NOT EXISTS remixed_from UUID;

-- from lib/community-server.ts
ALTER TABLE community_items DROP CONSTRAINT IF EXISTS community_items_kind_check;

-- from lib/community-server.ts
ALTER TABLE community_items ADD CONSTRAINT community_items_kind_check CHECK (kind IN ('song', 'sample', 'preset', 'recipe', 'pack', 'project', 'theme', 'kit', 'pattern', 'post', 'clip'));

-- from lib/community-server.ts
ALTER TABLE community_items ADD COLUMN IF NOT EXISTS author_username TEXT;

-- from lib/community-server.ts
ALTER TABLE community_collections ADD COLUMN IF NOT EXISTS author_username TEXT;

-- from lib/learn-schema.ts
ALTER TABLE learn_articles ADD COLUMN IF NOT EXISTS publish_at TEXT;

-- from lib/learn-schema.ts
ALTER TABLE learn_articles ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- from lib/learn-schema.ts
ALTER TABLE learn_articles ADD COLUMN IF NOT EXISTS repo_shadow BOOLEAN NOT NULL DEFAULT false;

-- from lib/pexels-bg.ts
ALTER TABLE pexels_bg ADD COLUMN IF NOT EXISTS block_edits TEXT[] NOT NULL DEFAULT '{}';

-- from lib/project-access.ts
ALTER TABLE projects ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'private';

-- from lib/project-access.ts
ALTER TABLE project_members ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'view';

-- from lib/project-access.ts
ALTER TABLE project_members ALTER COLUMN role SET DEFAULT 'view';

-- from lib/project-access.ts
ALTER TABLE project_members ADD COLUMN IF NOT EXISTS user_id TEXT;

-- from lib/subscription.ts
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- from lib/subscription.ts
ALTER TABLE subscriptions ALTER COLUMN created_at SET DEFAULT NOW();

-- ──────────────────────────────────────────────────────────────────────────
-- Indexes (36) — after the alters that add their columns
-- ──────────────────────────────────────────────────────────────────────────

-- from app/api/app-history/route.ts
CREATE INDEX IF NOT EXISTS app_history_user_slug_idx ON app_history (user_id, app_slug);

-- from app/api/folders/route.ts
CREATE INDEX IF NOT EXISTS folders_user_idx ON folders (user_id);

-- from app/api/library/items/route.ts
CREATE INDEX IF NOT EXISTS user_library_items_user_idx ON user_library_items (user_id, type);

-- from app/api/library/route.ts
CREATE INDEX IF NOT EXISTS user_sounds_user_idx ON user_sounds (user_id);

-- from app/api/media/presign-upload/route.ts
CREATE INDEX IF NOT EXISTS upload_log_user_idx ON upload_log (user_id);

-- from app/api/projects/[id]/versions/route.ts
CREATE INDEX IF NOT EXISTS project_versions_project_idx ON project_versions (project_id, created_at DESC);

-- from lib/admin-audit.ts
CREATE INDEX IF NOT EXISTS admin_audit_id_desc_idx ON admin_audit (id DESC);

-- from lib/affiliates.ts
CREATE INDEX IF NOT EXISTS affiliate_commissions_code_idx ON affiliate_commissions (code);

-- from lib/affiliates.ts
CREATE INDEX IF NOT EXISTS affiliate_commissions_code_user_idx ON affiliate_commissions (code, user_id);

-- from lib/affiliates.ts
CREATE INDEX IF NOT EXISTS affiliate_payouts_code_idx ON affiliate_payouts (code);

-- from lib/affiliates.ts
CREATE UNIQUE INDEX IF NOT EXISTS affiliates_tax_token_idx ON affiliates (tax_token) WHERE tax_token IS NOT NULL;

-- from lib/affiliates.ts
CREATE INDEX IF NOT EXISTS affiliates_stripe_account_idx ON affiliates (stripe_account_id) WHERE stripe_account_id IS NOT NULL;

-- from lib/codes.ts
CREATE INDEX IF NOT EXISTS code_redemptions_user_idx ON code_redemptions (user_id);

-- from lib/codes.ts
CREATE INDEX IF NOT EXISTS code_redemptions_user_kind_idx ON code_redemptions (user_id, kind);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_items_remixed_from_idx ON community_items (remixed_from);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_comments_item_idx ON community_comments (item_id, created_at);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_comments_user_idx ON community_comments (user_id, created_at);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_collections_user_idx ON community_collections (user_id, created_at DESC);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_collections_author_idx ON community_collections (author_name);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_collection_items_idx ON community_collection_items (collection_id, position);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_items_kind_idx ON community_items (kind, created_at DESC);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_items_created_idx ON community_items (created_at DESC);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_items_author_idx ON community_items (author_name);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_items_user_idx ON community_items (user_id);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_votes_user_idx ON community_votes (user_id);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_items_username_idx ON community_items (author_username);

-- from lib/community-server.ts
CREATE INDEX IF NOT EXISTS community_collections_username_idx ON community_collections (author_username);

-- from lib/notifications-server.ts
CREATE INDEX IF NOT EXISTS notifications_user_idx ON notifications (user_id, created_at DESC);

-- from lib/pexels-bg.ts
CREATE INDEX IF NOT EXISTS pexels_bg_status_idx ON pexels_bg (status, category);

-- from lib/reading-progress.ts
CREATE INDEX IF NOT EXISTS article_reads_user_idx ON article_reads (user_id);

-- from lib/track-embeddings.ts
CREATE INDEX IF NOT EXISTS track_embeddings_vec_idx ON track_embeddings USING hnsw (embedding vector_cosine_ops);

-- from lib/user-crm.ts
CREATE INDEX IF NOT EXISTS user_note_entries_user_idx ON user_note_entries (user_id, created_at DESC);

-- from lib/user-crm.ts
CREATE INDEX IF NOT EXISTS user_tasks_open_idx ON user_tasks (user_id) WHERE done_at IS NULL;

-- from lib/user-crm.ts
CREATE INDEX IF NOT EXISTS user_tasks_due_idx ON user_tasks (due_at) WHERE done_at IS NULL;

-- from lib/webhook-log.ts
CREATE INDEX IF NOT EXISTS webhook_events_recent ON webhook_events (received_at DESC);

-- from db/schema.legacy.sql (only definition anywhere)
CREATE INDEX IF NOT EXISTS projects_user_id_idx ON projects (user_id);
