'use client'

import { useState } from 'react'
import Link from 'next/link'
import type { SongMetadata, SplitRow, CreditLine, SampleUse, TimelineEvent, Contributor, ProjectAdmin } from '@/lib/project-admin'

// Inlined (not imported from project-admin) so this client component doesn't pull
// that server-only module — it imports @/lib/db, which can't run in the browser.
function fmtDuration(sec: number): string {
  const s = Math.max(0, Math.round(sec))
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
}

const card: React.CSSProperties = { background: 'var(--bg-surface, #17171b)', border: '1px solid var(--border, #26262b)', borderRadius: 12, padding: '18px 20px' }
const label: React.CSSProperties = { fontSize: 11, fontWeight: 700, letterSpacing: '0.05em', textTransform: 'uppercase', color: 'var(--text-muted, #a3a2b5)' }
const muted = 'var(--text-muted, #a3a2b5)'

type Tab = 'overview' | 'splits' | 'samples' | 'provenance' | 'release' | 'money'
const TABS: { id: Tab; label: string; tier?: number }[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'splits', label: 'Splits & Credits' },
  { id: 'samples', label: 'Samples' },
  { id: 'provenance', label: 'Provenance' },
  { id: 'release', label: 'Release', tier: 2 },
  { id: 'money', label: 'Money', tier: 3 },
]

export function HubClient({ projectId, metadata, contributors, splits: initialSplits, credits, samples, timeline, overlay, canEdit }: {
  projectId: string
  metadata: SongMetadata
  contributors: Contributor[]
  splits: SplitRow[]
  credits: CreditLine[]
  samples: SampleUse[]
  timeline: TimelineEvent[]
  overlay: ProjectAdmin
  canEdit: boolean
}) {
  const [tab, setTab] = useState<Tab>('overview')
  const [splits, setSplits] = useState(initialSplits)
  const [meta, setMeta] = useState(overlay.metadata ?? {})
  const [toast, setToast] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const flash = (m: string) => { setToast(m); setTimeout(() => setToast(null), 2800) }

  const splitTotal = splits.reduce((n, r) => n + (Number(r.pct) || 0), 0)

  async function save() {
    if (!canEdit) return
    setSaving(true)
    const splitOverrides: Record<string, number> = {}
    for (const r of splits) splitOverrides[r.name] = Number(r.pct) || 0
    try {
      const res = await fetch(`/api/lab/${projectId}`, {
        method: 'PUT', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ splitOverrides, metadata: meta }),
      })
      flash(res.ok ? 'Saved' : 'Save failed')
    } catch { flash('Save failed') }
    finally { setSaving(false) }
  }

  function copy(text: string, what: string) {
    if (navigator.clipboard) navigator.clipboard.writeText(text).then(() => flash(`${what} copied`)).catch(() => flash('Copy failed'))
  }
  const splitSheetText = () =>
    `SPLIT SHEET — "${metadata.title}"\n${metadata.bpm} BPM · ${metadata.keyLabel} · ${fmtDuration(metadata.durationSec)}\n\n` +
    splits.map(r => `${r.pct}%  ${r.name} (${r.role})`).join('\n') +
    `\n\nTotal: ${splitTotal}%\nGenerated by 100Lights`
  const creditsText = () =>
    `"${metadata.title}"\n\n` + credits.map(c => `${c.role}: ${c.who}`).join('\n')

  return (
    <main style={{ maxWidth: 860, margin: '0 auto', padding: '28px 20px 80px', color: 'var(--text-primary, #f1f0ff)' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}>
        <div>
          <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#a78bfa', marginBottom: 6 }}>Project Hub · Lab</div>
          <h1 style={{ fontSize: 26, fontWeight: 800, letterSpacing: '-0.01em', margin: 0 }}>{metadata.title}</h1>
          <div style={{ fontSize: 12.5, color: muted, marginTop: 5 }}>
            {metadata.bpm} BPM · {metadata.keyLabel} · {metadata.timeSignature} · {fmtDuration(metadata.durationSec)} · {metadata.trackCount} tracks
          </div>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <Link href={`/projects/${projectId}`} style={{ ...btn, textDecoration: 'none' }}>✎ Open in studio</Link>
          {canEdit && <button onClick={save} disabled={saving} style={{ ...btn, background: 'var(--accent, #7c3aed)', color: '#fff', border: 'none', opacity: saving ? 0.6 : 1 }}>{saving ? 'Saving…' : 'Save'}</button>}
        </div>
      </div>

      {/* Tabs */}
      <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap', margin: '20px 0 18px', borderBottom: '1px solid var(--border, #26262b)', paddingBottom: 0 }}>
        {TABS.map(t => (
          <button key={t.id} onClick={() => setTab(t.id)} style={{
            background: 'none', border: 'none', cursor: 'pointer', padding: '8px 12px', fontSize: 13, fontWeight: 600,
            color: tab === t.id ? 'var(--text-primary, #f1f0ff)' : muted,
            borderBottom: tab === t.id ? '2px solid #a78bfa' : '2px solid transparent', marginBottom: -1,
            display: 'flex', alignItems: 'center', gap: 6,
          }}>
            {t.label}{t.tier && <span style={{ fontSize: 9, fontWeight: 800, color: '#facc15', background: 'rgba(250,204,21,0.12)', borderRadius: 4, padding: '1px 5px' }}>SOON</span>}
          </button>
        ))}
      </div>

      {tab === 'overview' && (
        <section style={{ display: 'grid', gap: 14 }}>
          <div style={card}>
            <div style={label}>Metadata sheet · auto-generated</div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))', gap: 14, marginTop: 12 }}>
              <Field k="Title" v={metadata.title} />
              <Field k="Tempo" v={`${metadata.bpm} BPM`} />
              <Field k="Key" v={metadata.keyLabel} />
              <Field k="Time sig" v={metadata.timeSignature} />
              <Field k="Duration" v={fmtDuration(metadata.durationSec)} />
              <Field k="Tracks" v={String(metadata.trackCount)} />
            </div>
            {metadata.instruments.length > 0 && <div style={{ marginTop: 12, fontSize: 12.5, color: muted }}>Instruments: {metadata.instruments.join(', ')}</div>}
          </div>
          <div style={card}>
            <div style={label}>Release details</div>
            <p style={{ fontSize: 11.5, color: muted, margin: '4px 0 12px' }}>Not derivable from the audio — fill these in for distributors. Saved with the project.</p>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12 }}>
              <Input k="Genre" v={meta.genre ?? ''} onChange={v => setMeta(m => ({ ...m, genre: v }))} disabled={!canEdit} />
              <Input k="Mood" v={meta.mood ?? ''} onChange={v => setMeta(m => ({ ...m, mood: v }))} disabled={!canEdit} />
              <Input k="ISRC" v={meta.isrc ?? ''} onChange={v => setMeta(m => ({ ...m, isrc: v }))} disabled={!canEdit} placeholder="e.g. US-XXX-YY-NNNNN" />
              <Input k="Release date" v={meta.releaseDate ?? ''} onChange={v => setMeta(m => ({ ...m, releaseDate: v }))} disabled={!canEdit} placeholder="YYYY-MM-DD" />
            </div>
          </div>
        </section>
      )}

      {tab === 'splits' && (
        <section style={{ display: 'grid', gap: 14 }}>
          <div style={card}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div style={label}>Split sheet · from your collaborators</div>
              <button onClick={() => copy(splitSheetText(), 'Split sheet')} style={miniBtn}>Copy</button>
            </div>
            <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 12, fontSize: 13.5 }}>
              <tbody>
                {splits.map((r, i) => (
                  <tr key={r.name + i} style={{ borderTop: i ? '1px solid var(--border,#26262b)' : 'none' }}>
                    <td style={{ padding: '9px 0', fontWeight: 600 }}>{r.name}</td>
                    <td style={{ padding: '9px 0', color: muted, fontSize: 12 }}>{r.role}</td>
                    <td style={{ padding: '9px 0', textAlign: 'right', width: 90 }}>
                      <input type="number" min={0} max={100} step={0.5} value={r.pct} disabled={!canEdit}
                        onChange={e => { const pct = Number(e.target.value); setSplits(s => s.map((x, j) => j === i ? { ...x, pct } : x)) }}
                        style={{ width: 64, textAlign: 'right', background: 'var(--bg-base,#0f0f11)', border: '1px solid var(--border,#26262b)', color: 'inherit', borderRadius: 6, padding: '4px 6px', fontSize: 13 }} /> %
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div style={{ marginTop: 10, fontSize: 12.5, color: Math.abs(splitTotal - 100) < 0.01 ? '#4ade80' : '#fb923c', fontWeight: 600 }}>
              Total: {Math.round(splitTotal * 10) / 10}% {Math.abs(splitTotal - 100) >= 0.01 && '— should sum to 100%'}
            </div>
          </div>
          <div style={card}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div style={label}>Credits · liner notes</div>
              <button onClick={() => copy(creditsText(), 'Credits')} style={miniBtn}>Copy</button>
            </div>
            <div style={{ display: 'grid', gap: 6, marginTop: 12 }}>
              {credits.map((c, i) => (
                <div key={i} style={{ fontSize: 13.5 }}><span style={{ color: muted }}>{c.role}: </span><b>{c.who}</b></div>
              ))}
            </div>
          </div>
        </section>
      )}

      {tab === 'samples' && (
        <section style={card}>
          <div style={label}>Sample usage & clearance · from the project&rsquo;s clips</div>
          <p style={{ fontSize: 11.5, color: muted, margin: '4px 0 12px' }}>Every sampled sound in this song and where it came from — only possible because the track was made here.</p>
          {samples.length === 0 ? <p style={{ fontSize: 13, color: muted }}>No sampled audio — all synths/MIDI. Nothing to clear.</p> : (
            <div style={{ display: 'grid', gap: 8 }}>
              {samples.map(s => (
                <div key={s.clipId} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10, padding: '10px 12px', background: 'var(--bg-base,#0f0f11)', borderRadius: 8, border: '1px solid var(--border,#26262b)' }}>
                  <div style={{ minWidth: 0 }}>
                    <div style={{ fontSize: 13.5, fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{s.clipName}</div>
                    <div style={{ fontSize: 11.5, color: muted }}>
                      {s.source === 'community' ? `Community sample${s.author ? ` · by ${s.author}` : ''}` : s.source === 'recording' ? 'Your recording / import' : 'Library sound'}
                    </div>
                  </div>
                  <span style={{ flexShrink: 0, fontSize: 10.5, fontWeight: 700, borderRadius: 999, padding: '3px 10px', ...clearancePill(s.clearance) }}>{clearanceLabel(s.clearance)}</span>
                </div>
              ))}
            </div>
          )}
        </section>
      )}

      {tab === 'provenance' && (
        <section style={card}>
          <div style={label}>Proof of creation · this song&rsquo;s history</div>
          <p style={{ fontSize: 11.5, color: muted, margin: '4px 0 14px' }}>A dated record of how the track came together — useful for credits, disputes, and copyright.</p>
          <div style={{ display: 'grid', gap: 0 }}>
            {timeline.map((e, i) => (
              <div key={i} style={{ display: 'flex', gap: 12, padding: '9px 0', borderTop: i ? '1px solid var(--border,#26262b)' : 'none' }}>
                <div style={{ width: 96, flexShrink: 0, fontSize: 11.5, color: muted, fontVariantNumeric: 'tabular-nums' }}>{e.at ? new Date(e.at).toLocaleDateString() : '—'}</div>
                <div style={{ fontSize: 13.5 }}>{e.label}</div>
              </div>
            ))}
          </div>
        </section>
      )}

      {(tab === 'release' || tab === 'money') && (
        <section style={card}>
          <div style={label}>{tab === 'release' ? 'Release · Tier 2' : 'Money · Tier 3'}</div>
          <p style={{ fontSize: 13.5, color: 'var(--text-secondary,#cfceda)', lineHeight: 1.55, margin: '10px 0 14px' }}>
            {tab === 'release'
              ? 'A guided release flow — cover art, ISRC/UPC assignment, split e-sign, and hand-off to distribution — building on the metadata + splits already generated here.'
              : 'Royalty-split payouts (on the existing payout rails), freelance invoicing, and tax docs — driven by the splits above.'}
          </p>
          <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13, color: muted, display: 'grid', gap: 5 }}>
            {(tab === 'release'
              ? ['Release checklist (metadata ✓, splits ✓, cover, ISRC)', 'Assign ISRC / UPC codes', 'Split-sheet e-signature', 'Distribution hand-off', 'EPK generator']
              : ['Split payouts via Stripe Connect', 'Freelance production invoicing', 'Tax documents', 'Sync-licensing income']
            ).map(x => <li key={x}>{x}</li>)}
          </ul>
        </section>
      )}

      {toast && (
        <div role="status" style={{ position: 'fixed', bottom: 24, left: '50%', transform: 'translateX(-50%)', zIndex: 1000, background: '#1e1e1e', border: '1px solid var(--border,#26262b)', borderRadius: 8, padding: '9px 16px', fontSize: 12.5, boxShadow: '0 8px 30px rgba(0,0,0,0.5)' }}>{toast}</div>
      )}
    </main>
  )
}

const btn: React.CSSProperties = { display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 12.5, fontWeight: 600, color: 'var(--text-secondary,#cfceda)', background: 'var(--bg-surface,#17171b)', border: '1px solid var(--border,#26262b)', borderRadius: 8, padding: '7px 13px', cursor: 'pointer' }
const miniBtn: React.CSSProperties = { fontSize: 11, fontWeight: 600, color: muted, background: 'transparent', border: '1px solid var(--border,#26262b)', borderRadius: 999, padding: '3px 11px', cursor: 'pointer' }

function Field({ k, v }: { k: string; v: string }) {
  return <div><div style={{ fontSize: 10.5, color: muted, textTransform: 'uppercase', letterSpacing: '0.04em' }}>{k}</div><div style={{ fontSize: 15, fontWeight: 700, marginTop: 2 }}>{v}</div></div>
}
function Input({ k, v, onChange, disabled, placeholder }: { k: string; v: string; onChange: (v: string) => void; disabled?: boolean; placeholder?: string }) {
  return (
    <label style={{ display: 'block' }}>
      <span style={{ fontSize: 10.5, color: muted, textTransform: 'uppercase', letterSpacing: '0.04em' }}>{k}</span>
      <input value={v} onChange={e => onChange(e.target.value)} disabled={disabled} placeholder={placeholder}
        style={{ display: 'block', width: '100%', marginTop: 4, background: 'var(--bg-base,#0f0f11)', border: '1px solid var(--border,#26262b)', color: 'inherit', borderRadius: 7, padding: '7px 9px', fontSize: 13, boxSizing: 'border-box' }} />
    </label>
  )
}
function clearancePill(c: SampleUse['clearance']): React.CSSProperties {
  if (c === 'owned') return { color: '#4ade80', background: 'rgba(74,222,128,0.12)' }
  if (c === 'community') return { color: '#a78bfa', background: 'rgba(167,139,250,0.14)' }
  return { color: '#fb923c', background: 'rgba(251,146,60,0.14)' }
}
function clearanceLabel(c: SampleUse['clearance']): string {
  return c === 'owned' ? 'Yours' : c === 'community' ? 'Community · attribute' : 'Needs clearance'
}
