// Auto-generated by scripts/fetch-bg-clips.mjs — nature clip ids that have real, hosted-
// quality footage bundled at public/bg/nature/<id>.mp4 (with a real <id>.jpg poster). Any id
// NOT listed here falls back to its procedural .webm loop. Do not edit by hand; re-run
// `npm run bg:fetch` to refresh.
export const FETCHED_NATURE: string[] = []
