// Background library for the Music Video live visualizer.
//
// Two kinds of clip:
//  • kind:'image' — bundled generative backgrounds (public/bg/generative/*.jpg),
//    generated by scripts/gen-bg-images.mjs. Real, detailed, work offline NOW.
//  • kind:'video' — the curated nature clips (Aerial/Beach/Mountains/Animals/City)
//    that STREAM online from a CDN/R2 base (NEXT_PUBLIC_BG_CDN) as <id>.mp4, with a
//    small poster cached offline at public/bg/previews/<id>.jpg. Until you host a
//    clip it shows its poster / a gradient tint.
//
// Adding a clip = add a row here (no code change). Hosting the nature clips + a CSP
// media-src for the CDN are the ops step; the bundled images need neither.

export interface BgClip {
  id: string
  category: BgCategory
  title: string
  kind: 'image' | 'video'
  preview: string   // thumbnail / poster (same-origin, cached offline)
  src: string       // full asset (image is same-origin; video streams from the CDN)
  tint: string      // gradient shown until the asset loads (and if it 404s)
}

export const BG_CATEGORIES = ['Patterns', 'Aerial', 'Beach', 'Mountains', 'Animals', 'City', 'Ambient'] as const
export type BgCategory = typeof BG_CATEGORIES[number]

const CDN = (process.env.NEXT_PUBLIC_BG_CDN || '').replace(/\/$/, '')

// Bundled generative images — render immediately, offline, no hosting.
const GENERATIVE: { id: string; title: string; tint: string }[] = [
  { id: 'nebula-violet', title: 'Nebula', tint: 'linear-gradient(135deg,#4c1d95,#db2777)' },
  { id: 'aurora-teal', title: 'Aurora', tint: 'linear-gradient(135deg,#0ea5e9,#34d399)' },
  { id: 'sunset-haze', title: 'Sunset haze', tint: 'linear-gradient(135deg,#f59e0b,#f43f5e)' },
  { id: 'ocean-deep', title: 'Deep ocean', tint: 'linear-gradient(135deg,#082f49,#22d3ee)' },
  { id: 'ember-glow', title: 'Ember', tint: 'linear-gradient(135deg,#7c2d12,#f97316)' },
  { id: 'bokeh-lights', title: 'Bokeh lights', tint: 'linear-gradient(135deg,#4c1d95,#22d3ee)' },
  { id: 'bokeh-warm', title: 'Warm bokeh', tint: 'linear-gradient(135deg,#7c2d12,#fbbf24)' },
  { id: 'synthwave-grid', title: 'Synthwave', tint: 'linear-gradient(135deg,#7c3aed,#db2777)' },
  { id: 'particles-cyan', title: 'Particles', tint: 'linear-gradient(135deg,#0891b2,#a78bfa)' },
  { id: 'waves-blue', title: 'Blue waves', tint: 'linear-gradient(135deg,#0369a1,#38bdf8)' },
  { id: 'liquid-magma', title: 'Magma', tint: 'linear-gradient(135deg,#7c2d12,#fbbf24)' },
  { id: 'starfield-deep', title: 'Starfield', tint: 'linear-gradient(135deg,#1e1b4b,#db2777)' },
  { id: 'plasma-neon', title: 'Plasma', tint: 'linear-gradient(135deg,#22d3ee,#f472b6)' },
  { id: 'plasma-sunset', title: 'Sunset plasma', tint: 'linear-gradient(135deg,#f59e0b,#7c3aed)' },
  { id: 'mountains-dusk', title: 'Mountains', tint: 'linear-gradient(135deg,#7c3aed,#fbbf24)' },
]

// Curated nature clips — stream online; poster cached offline.
const NATURE: { id: string; category: BgCategory; title: string; tint: string }[] = [
  { id: 'aerial-coastline', category: 'Aerial', title: 'Coastline from above', tint: 'linear-gradient(135deg,#0e7490,#22d3ee)' },
  { id: 'aerial-forest', category: 'Aerial', title: 'Forest canopy', tint: 'linear-gradient(135deg,#065f46,#34d399)' },
  { id: 'aerial-desert', category: 'Aerial', title: 'Desert dunes', tint: 'linear-gradient(135deg,#b45309,#fbbf24)' },
  { id: 'beach-waves', category: 'Beach', title: 'Rolling waves', tint: 'linear-gradient(135deg,#0369a1,#38bdf8)' },
  { id: 'beach-sunset', category: 'Beach', title: 'Beach sunset', tint: 'linear-gradient(135deg,#c2410c,#f59e0b)' },
  { id: 'mountains-peaks', category: 'Mountains', title: 'Windy peaks', tint: 'linear-gradient(135deg,#334155,#94a3b8)' },
  { id: 'mountains-valley', category: 'Mountains', title: 'Misty valley', tint: 'linear-gradient(135deg,#1e3a5f,#64748b)' },
  { id: 'animals-birds', category: 'Animals', title: 'Birds in flight', tint: 'linear-gradient(135deg,#0c4a6e,#7dd3fc)' },
  { id: 'animals-jellyfish', category: 'Animals', title: 'Jellyfish drift', tint: 'linear-gradient(135deg,#4c1d95,#c084fc)' },
  { id: 'city-night', category: 'City', title: 'City at night', tint: 'linear-gradient(135deg,#111827,#a78bfa)' },
  { id: 'city-timelapse', category: 'City', title: 'Traffic trails', tint: 'linear-gradient(135deg,#7c2d12,#f97316)' },
]

export const BG_LIBRARY: BgClip[] = [
  ...GENERATIVE.map(g => ({
    id: g.id, category: 'Patterns' as BgCategory, title: g.title, kind: 'image' as const,
    preview: `/bg/generative/${g.id}.jpg`, src: `/bg/generative/${g.id}.jpg`, tint: g.tint,
  })),
  ...NATURE.map(c => ({
    ...c, kind: 'video' as const,
    preview: `/bg/previews/${c.id}.jpg`, src: CDN ? `${CDN}/${c.id}.mp4` : `/bg/clips/${c.id}.mp4`,
  })),
]

export const clipsByCategory = (cat: BgCategory): BgClip[] => BG_LIBRARY.filter(c => c.category === cat)
export const clipById = (id: string): BgClip | undefined => BG_LIBRARY.find(c => c.id === id)
