// Auto-generated by admin panel — do not edit manually.
// Run "Bake in corrections" in /admin to regenerate from learned corrections.
import type { HitSpectral } from './beat-features'

export const CORRECTION_SEEDS: HitSpectral[] = []

export const SPLIT_PAIR_SEEDS: Array<{ distinctSpectral: HitSpectral; confusedWithSpectral: HitSpectral }> = []
