// ── Built-in starter TEMPLATES ───────────────────────────────────────────────
// Open starting points shown on the New Project screen so users don't begin from
// a blank timeline. Each `id` maps to a dawProject at public/templates/<id>.json
// (generated by scripts/templates.mjs). Community/user templates are shared as
// `kind:'project'` community items (lib/community.ts shareProjectStarter) and
// opened via /new?starter=<id> — the same path as remixable starters.

export interface StarterTemplate {
  id: string          // → public/templates/<id>.json
  name: string
  description: string
  tags: string[]
  tempo: number
  keyLabel: string
  instruments: string[]
}

export const BUILT_IN_TEMPLATES: StarterTemplate[] = [
  {
    id: 'template-cinematic',
    name: 'Cinematic',
    description: 'Sustained sub-bass, grand piano and a warm pad — slow, open and moody. Great for cinematic or dark-pop ideas.',
    tags: ['ambient', 'cinematic', 'minor'],
    tempo: 90, keyLabel: 'A minor',
    instruments: ['Sub Bass', 'Grand Piano', 'Warm Pad'],
  },
  {
    id: 'template-lofi',
    name: 'Lo-fi',
    description: 'Rhodes, a soft choir pad and sub — mellow and warm, a chilled backdrop to write over.',
    tags: ['lofi', 'chill', 'minor'],
    tempo: 82, keyLabel: 'D minor',
    instruments: ['Sub Bass', 'Rhodes', 'Choir Pad'],
  },
  {
    id: 'template-warm',
    name: 'Warm',
    description: 'Electric piano, synth strings and sub — brighter and uplifting, a major-key starting point.',
    tags: ['ambient', 'warm', 'major'],
    tempo: 100, keyLabel: 'C major',
    instruments: ['Sub Bass', 'Warm EP', 'Synth Strings'],
  },
]

export function getTemplate(id: string): StarterTemplate | undefined {
  return BUILT_IN_TEMPLATES.find(t => t.id === id)
}
