export const metadata = {
  title: '100Lights — Privacy Policy',
  description: 'How 100Lights collects, uses, and protects your information, your uploaded content, and your rights.',
  alternates: { canonical: 'https://100lights.com/legal/privacy' },
  openGraph: { title: '100Lights — Privacy Policy', description: 'How 100Lights collects, uses, and protects your information.', url: 'https://100lights.com/legal/privacy' },
}

export default function PrivacyPage() {
  return (
    <div style={{ background: 'var(--bg-base)', minHeight: '100vh' }}>
      <div className="max-w-3xl mx-auto px-8 py-16">
        <h1 className="text-3xl font-bold mb-2" style={{ color: 'var(--text-primary)' }}>Privacy Policy</h1>
        <p className="text-sm mb-12" style={{ color: 'var(--text-muted)' }}>Last updated: June 2026</p>

        {[
          {
            title: '1. Information We Collect',
            body: 'We collect information you provide directly (name, email, payment details), information generated by your use of the Service (uploaded files, projects, transcripts, usage logs), and technical data (IP address, browser type, device identifiers) collected automatically.',
          },
          {
            title: '2. How We Use Your Information',
            body: 'We use your information to provide and improve the Service, process payments, send transactional emails (receipts, account notices), enforce our Terms of Service, and comply with legal obligations. We do not sell your personal information.',
          },
          {
            title: '3. Your Uploaded Content',
            body: 'Files you upload are stored securely in Cloudflare R2 and are only accessible to you via time-limited signed URLs. When you request transcription, audio is processed by a third-party speech-to-text service (Deepgram) solely to deliver that feature. These providers are bound by data processing agreements.',
          },
          {
            title: '4. Third-Party Services',
            body: 'We use the following sub-processors: Clerk (authentication), Neon (database), Cloudflare R2 (file storage), Deepgram (speech-to-text transcription), Stripe (payments), Sentry (error monitoring). Each operates under its own privacy policy.',
          },
          {
            title: '5. Data Retention',
            body: 'We retain your account data for as long as your account is active. Uploaded media files are retained until you delete them or your account is terminated. Usage logs are retained for up to 90 days. After account deletion, all data is purged within 30 days.',
          },
          {
            title: '6. Security',
            body: 'We use industry-standard security measures including encryption in transit (TLS) and at rest, private cloud storage with signed URL access, and regular security reviews. No system is completely secure; we encourage you to use a strong password and keep credentials private.',
          },
          {
            title: '7. Your Rights',
            body: 'Depending on your jurisdiction, you may have rights to access, correct, export, or delete your personal data. To exercise these rights, contact us at privacy@100lights.com. We will respond within 30 days.',
          },
          {
            title: '8. Cookies',
            body: 'We use essential cookies for authentication (managed by Clerk) and session management. We do not use advertising or tracking cookies. You can control cookies in your browser settings, though disabling essential cookies will prevent you from logging in.',
          },
          {
            title: '9. Children',
            body: 'The Service is not directed at children under 13. We do not knowingly collect personal information from children. If we learn we have collected data from a child, we will delete it promptly.',
          },
          {
            title: '10. Changes to This Policy',
            body: 'We may update this Privacy Policy. We will notify you of material changes by email. Continued use of the Service after notice constitutes acceptance.',
          },
          {
            title: '11. Contact',
            body: 'Privacy questions or requests: privacy@100lights.com.',
          },
        ].map(({ title, body }) => (
          <div key={title} className="mb-8">
            <h2 className="text-base font-semibold mb-2" style={{ color: 'var(--text-primary)' }}>{title}</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{body}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
