import { writeFile } from 'fs/promises'
import path from 'path'
import { isAdmin } from '@/lib/admin-auth'

export async function POST(req: Request) {
  if (!await isAdmin()) return Response.json({ error: 'Unauthorized' }, { status: 401 })

  const { correctionSeeds, splitPairs } = await req.json()

  const code = `// Auto-generated by admin panel — do not edit manually.
// Run "Bake in corrections" in /admin to regenerate from learned corrections.
// Generated: ${new Date().toISOString()}
import type { HitSpectral } from './beat-features'

export const CORRECTION_SEEDS: HitSpectral[] = ${JSON.stringify(correctionSeeds, null, 2)}

export const SPLIT_PAIR_SEEDS: Array<{ distinctSpectral: HitSpectral; confusedWithSpectral: HitSpectral }> = ${JSON.stringify(splitPairs, null, 2)}
`

  try {
    await writeFile(path.join(process.cwd(), 'lib/cluster-seeds.ts'), code, 'utf-8')
    return Response.json({ ok: true })
  } catch (err) {
    return Response.json({ error: String(err) }, { status: 500 })
  }
}
