// 100 additional DAW recipe candidates (chord progressions + a few bass grounds), same shape as the
// RECIPES array in seed-recipes.mjs. Wired in by spreading EXTRA_RECIPES into that array before seeding.
// Progressions are voiced with the chord builders below so every triad/7th is harmonically correct.

// ── spec helpers (mirror seed-recipes.mjs) ───────────────────────────────────
const N = (pitch, startBeat, durationBeats, velocity = 96) => ({ pitch, startBeat, durationBeats, velocity })
const chord = (start, dur, pitches) => pitches.map(p => N(p, start, dur))
const progSpec = (trackName, beatsPer, chords) => {
  const notes = []
  chords.forEach((pitches, i) => notes.push(...chord(i * beatsPer, beatsPer, pitches)))
  return { trackName, instrument: { type: 'none', params: {} }, isDrumClip: false, durationBeats: chords.length * beatsPer, usePreset: true, notes }
}
const bassSpec = (trackName, beatsPer, roots) => ({
  trackName, instrument: { type: 'none', params: {} }, isDrumClip: false, durationBeats: roots.length * beatsPer, usePreset: true,
  notes: roots.map((p, i) => N(p, i * beatsPer, beatsPer, 100)),
})

// ── chord builders (root = MIDI note) ────────────────────────────────────────
const maj  = r => [r, r + 4, r + 7]
const min  = r => [r, r + 3, r + 7]
const dim  = r => [r, r + 3, r + 6]
const aug  = r => [r, r + 4, r + 8]
const sus2 = r => [r, r + 2, r + 7]
const sus4 = r => [r, r + 5, r + 7]
const maj7 = r => [r, r + 4, r + 7, r + 11]
const min7 = r => [r, r + 3, r + 7, r + 10]
const dom7 = r => [r, r + 4, r + 7, r + 10]
const m7b5 = r => [r, r + 3, r + 6, r + 10]
const dim7 = r => [r, r + 3, r + 6, r + 9]
const add9 = r => [r, r + 4, r + 7, r + 14]
const six  = r => [r, r + 4, r + 7, r + 9]
const m6   = r => [r, r + 3, r + 7, r + 9]
// note constants (octave 3–4 so root-position triads sit ~48–72)
const C = 60, Cs = 61, D = 62, Ds = 63, E = 64, F = 65, Fs = 66, G = 55, Gs = 56, A = 57, As = 58, B = 59
// lower-octave helpers for keys that want a lower root
const c = 48, d = 50, e = 52, f = 53, g = 55, a = 57, b = 59

const R = (id, title, genre, tagline, annotation, spec, source = 'Original recipe (theory-derived)') =>
  ({ id, title, genre, tagline, annotation, spec, source })

export const EXTRA_RECIPES = [
  // ── POP ──────────────────────────────────────────────────────────────────
  R('pop-axis-c', 'Axis I–V–vi–IV (C)', 'Pop', 'C → G → Am → F: the four chords behind a thousand hits.',
    ['The "axis of awesome" loop — endlessly singable because it never fully rests, always turning back to I.', 'Swap the order (vi–IV–I–V) for a more yearning, minor-leaning version of the same four chords.'],
    progSpec('Recipe: Axis (C)', 4, [maj(60), maj(67), min(69), maj(65)])),
  R('pop-sensitive-a', 'Sensitive vi–IV–I–V (C)', 'Pop', 'Am → F → C → G: the emotional-ballad rotation of the axis.',
    ['Starting on vi makes it feel like it opens mid-thought — great for a verse that resolves into the chorus on I.', 'The same four chords as the axis, just rotated to begin on the relative minor.'],
    progSpec('Recipe: Sensitive (C)', 4, [min(69), maj(65), maj(60), maj(67)])),
  R('pop-50s-c', '50s doo-wop I–vi–IV–V (C)', 'Pop', 'C → Am → F → G: the "Stand By Me" changes.',
    ['The vi (Am) is the whole charm — a soft minor cloud between two bright majors before V drives home.', 'Put the bass on a walking C–A–F–G and it instantly reads as doo-wop / early rock.'],
    progSpec('Recipe: 50s (C)', 4, [maj(60), min(69), maj(65), maj(67)])),
  R('pop-royal-road-c', 'Royal Road IV–V–iii–vi (C)', 'Pop', 'F → G → Em → Am: the J-pop/anime "royal road".',
    ['The iii→vi motion (Em→Am) is the signature — a bittersweet turn that Japanese pop leans on constantly.', 'It resolves onto vi, not I, so it feels wistful even at full energy.'],
    progSpec('Recipe: Royal Road (C)', 4, [maj(65), maj(67), min(64), min(69)])),
  R('pop-i-iii-vi-iv', 'Bright I–iii–vi–IV (C)', 'Pop', 'C → Em → Am → F: gentle stepwise descent in the top voice.',
    ['iii bridges I and vi smoothly — the three share tones, so the movement is subtle and warm.', 'Common in acoustic pop; try arpeggiating each chord to expose the descending line.'],
    progSpec('Recipe: I–iii–vi–IV', 4, [maj(60), min(64), min(69), maj(65)])),
  R('pop-iv-i-v-vi', 'Anthemic IV–I–V–vi (C)', 'Pop', 'F → C → G → Am: builds up, lands on the minor.',
    ['Opening on IV gives an uplifted, mid-air feeling; ending on vi keeps it from resolving too neatly.', 'A staple of stadium pop pre-choruses.'],
    progSpec('Recipe: IV–I–V–vi', 4, [maj(65), maj(60), maj(67), min(69)])),
  R('pop-i-v-vi-iii-iv', 'Ballad I–V–vi–iii–IV (C)', 'Pop', 'C → G → Am → Em → F: the extended axis with a iii.',
    ['Adding iii (Em) before IV stretches the loop to five chords and delays the return home.', 'Great for a slow build where each bar needs a fresh colour.'],
    progSpec('Recipe: I–V–vi–iii–IV', 4, [maj(60), maj(67), min(69), min(64), maj(65)])),
  R('pop-vi-v-iv-v', 'Yearning vi–V–IV–V (A minor feel)', 'Pop', 'Am → G → F → G: hangs on tension, never resolves to I.',
    ['No tonic major ever appears — it just circles the minor, so it feels permanently unresolved and dramatic.', 'The repeated V (G) acts like a heartbeat pushing back to Am each time.'],
    progSpec('Recipe: vi–V–IV–V', 4, [min(69), maj(67), maj(65), maj(67)])),
  R('pop-i-iv-i-v', 'Simple I–IV–I–V (C)', 'Pop', 'C → F → C → G: three-chord bedrock.',
    ['The plainest pop/folk frame — I is home, IV is the lift, V is the pull back.', 'Everything else in pop is an ornament on these three chords.'],
    progSpec('Recipe: I–IV–I–V', 4, [maj(60), maj(65), maj(60), maj(67)])),
  R('pop-i-vi-iii-vii', 'Dreamy I–vi–iii–VII (C)', 'Pop', 'C → Am → Em → Bb: a borrowed bVII for lift.',
    ['The bVII (Bb) is borrowed from C Mixolydian — it brightens the ending without the leading-tone pull of a real V.', 'Common in indie and dream-pop; sounds nostalgic and slightly hazy.'],
    progSpec('Recipe: I–vi–iii–bVII', 4, [maj(60), min(69), min(64), maj(58)])),
  R('pop-add9-wash', 'Add9 wash I–V–vi–IV (C)', 'Pop', 'Cadd9 → Gadd9 → Am9 → Fadd9: the same axis, shimmering.',
    ['Adding the 9th to every chord gives that open, glassy modern-pop sheen (think ringing guitars / soft synths).', 'The shared 9ths make the changes blur together into a pad-like wash.'],
    progSpec('Recipe: Add9 axis', 4, [add9(60), add9(67), [69, 72, 76, 83], add9(65)])),
  R('pop-descending-c', 'Descending I–V6–vi–I6 (C)', 'Pop', 'C → G/B → Am → C/G: a stepwise falling bassline.',
    ['The bass walks C–B–A–G under held upper voices — the "line cliché" that makes ballads feel like they\'re sinking gently.', 'Voicing matters here: keep the top notes still and let only the bass move.'],
    progSpec('Recipe: Descending bass (C)', 4, [maj(60), [59, 67, 62], min(69), [55, 60, 64]])),

  // ── ROCK ───────────────────────────────────────────────────────────────────
  R('rock-i-iv-v', 'Rock I–IV–V (E)', 'Rock', 'E → A → B: the raw three-chord engine.',
    ['The oldest rock/blues frame — power and simplicity. V (B) always wants I (E) back.', 'Play them as power chords (root+5th) for the classic driving sound.'],
    progSpec('Recipe: Rock I–IV–V (E)', 4, [maj(52), maj(57), maj(59)])),
  R('rock-i-bvii-iv', 'Mixolydian I–bVII–IV (D)', 'Rock', 'D → C → G: the "Sweet Home"/Sympathy loop.',
    ['The bVII (C) is borrowed from Mixolydian — it replaces the leading-tone V and gives that classic-rock swagger.', 'No tension chord at all, so it can loop forever under a jam.'],
    progSpec('Recipe: I–bVII–IV (D)', 4, [maj(50), maj(60), maj(55)])),
  R('rock-i-v-iv', 'Anthem I–V–IV (A)', 'Rock', 'A → E → D: the wide-open arena change.',
    ['I–V–IV (as opposed to I–IV–V) resolves by stepping down from V to IV to I — feels triumphant and grounded.', 'The backbone of countless stadium singalongs.'],
    progSpec('Recipe: I–V–IV (A)', 4, [maj(57), maj(52), maj(50)])),
  R('rock-i-bvii-bvi-bvii', 'Aeolian i–bVII–bVI–bVII (E minor)', 'Rock', 'Em → D → C → D: brooding hard-rock climb.',
    ['All diatonic to E natural minor — the bVI (C) is the dark floor, bVII (D) the push back up.', 'A go-to for anthemic minor-key rock and metal verses.'],
    progSpec('Recipe: i–bVII–bVI–bVII (Em)', 4, [min(52), maj(50), maj(60), maj(50)])),
  R('rock-blues-i-iv', 'Riff I7–IV7 (A)', 'Rock', 'A7 → D7: the dominant-7 riff-rock vamp.',
    ['Dominant 7ths on both chords give it that gritty, unresolved blues-rock edge.', 'Sit on A7 for the verse and hit D7 for the change — instant garage energy.'],
    progSpec('Recipe: I7–IV7 (A)', 4, [dom7(57), dom7(50)])),
  R('rock-punk-i-v-vi-iv', 'Pop-punk I–V–vi–IV (D)', 'Rock', 'D → A → Bm → G: the axis at full gain.',
    ['Same four chords as pop, but downstroked power chords + fast tempo = pop-punk.', 'The Bm (vi) is where the "emotional" lyric always lands.'],
    progSpec('Recipe: Pop-punk axis (D)', 4, [maj(50), maj(57), min(59), maj(55)])),
  R('rock-grunge-i-iii-iv', 'Grunge I–biii–IV chromatic (E)', 'Rock', 'E → G → A: the chromatic bVI/biii crunch.',
    ['The bIII (G) is borrowed — a chromatic surprise against the E-major expectation, dark and heavy.', 'Trademark of 90s grunge; play loud and let the G chord grind.'],
    progSpec('Recipe: Grunge (E)', 4, [maj(52), maj(55), maj(57)])),

  // ── JAZZ ───────────────────────────────────────────────────────────────────
  R('jazz-251-major', 'Major ii–V–I (C)', 'Jazz', 'Dm7 → G7 → Cmaj7: the fundamental jazz cadence.',
    ['The engine of jazz harmony. The G7\'s tritone (B–F) resolves to Cmaj7\'s E–C — every other progression is a chain of these.', 'Practice it through all 12 keys; it\'s the ii–V–I you\'ll transpose forever.'],
    progSpec('Recipe: ii–V–I (C)', 4, [min7(62), dom7(55), maj7(60)])),
  R('jazz-251-minor', 'Minor ii–V–i (A minor)', 'Jazz', 'Bm7b5 → E7 → Am7: the minor two-five-one.',
    ['The ii is half-diminished (m7b5) and the V is a dominant with a b9 flavour — darker, more urgent than the major version.', 'The E7 borrows G# (the harmonic-minor leading tone) to pull hard into Am.'],
    progSpec('Recipe: ii–V–i (Am)', 4, [m7b5(59), dom7(52), min7(57)])),
  R('jazz-rhythm-changes', 'Rhythm changes I–vi–ii–V (Bb→C shown)', 'Jazz', 'Cmaj7 → Am7 → Dm7 → G7: the turnaround loop.',
    ['The "I Got Rhythm" A-section engine — a I–vi–ii–V that loops seamlessly, the most-played turnaround in jazz.', 'Every chord is a step in a cycle of descending fifths back to I.'],
    progSpec('Recipe: Rhythm changes', 2, [maj7(60), min7(57), min7(62), dom7(55)])),
  R('jazz-iii-vi-ii-v', 'Turnaround iii–vi–ii–V (C)', 'Jazz', 'Em7 → Am7 → Dm7 → G7: the long turnaround.',
    ['Extends the ii–V back two more steps in the cycle of fifths — a smooth four-chord walk home.', 'Used to fill the last bars of a chorus before repeating the head.'],
    progSpec('Recipe: iii–vi–ii–V (C)', 4, [min7(64), min7(57), min7(62), dom7(55)])),
  R('jazz-autumn-leaves', 'Autumn Leaves cycle (G major / E minor)', 'Jazz', 'Cm7 → F7 → Bbmaj7 → Ebmaj7: the standard\'s A-section.',
    ['A textbook chain of ii–V–I moving through relative major and minor — the go-to first standard for learning changes.', 'Notice it\'s just descending fifths: Cm–F–Bb–Eb.'],
    progSpec('Recipe: Autumn Leaves A', 4, [min7(60), dom7(53), maj7(58), maj7(63)])),
  R('jazz-birds-blues', 'Bird blues turnaround (F)', 'Jazz', 'Fmaj7 → Em7b5 → A7 → Dm7: Parker\'s reharmonised blues top.',
    ['Charlie Parker reharmonised the plain blues with extra ii–Vs — this is the first four bars of "Blues for Alice".', 'Each pair is a mini ii–V pulling to the next chord — dense, fast harmonic motion.'],
    progSpec('Recipe: Bird blues (F)', 2, [maj7(53), m7b5(64), dom7(57), min7(62)])),
  R('jazz-coltrane', 'Coltrane changes (major-3rd cycle)', 'Jazz', 'Cmaj7 → Eb7 → Abmaj7 → B7: giant-steps thirds.',
    ['Instead of fifths, the tonics move by major thirds (C–Ab–E), each reached by its own V — the "Giant Steps" trick.', 'Symmetrical and disorienting; a rite of passage for improvisers.'],
    progSpec('Recipe: Coltrane changes', 2, [maj7(60), dom7(63), maj7(56), dom7(59)])),
  R('jazz-bossa-251', 'Bossa ii–V–I with maj7 (F)', 'Jazz', 'Gm7 → C7 → Fmaj7 → Fmaj7: warm bossa cadence.',
    ['The same ii–V–I but relaxed onto a lingering Fmaj7 — the harmonic home of bossa nova.', 'Play it soft with a light clave and it becomes Jobim instantly.'],
    progSpec('Recipe: Bossa ii–V–I (F)', 4, [min7(55), dom7(60), maj7(53), maj7(53)])),
  R('jazz-modal-so-what', 'Modal Dorian vamp (D–Eb, "So What")', 'Jazz', 'Dm7 → Ebm7: a semitone shift between two modes.',
    ['Modal jazz drops functional chords — just two m7 chords a semitone apart, each held for many bars.', 'The Eb is the same shape shoved up one fret; improvise in D Dorian then Eb Dorian.'],
    progSpec('Recipe: So What vamp', 8, [min7(62), min7(63)])),
  R('jazz-minor-line-cliche', 'Minor line cliché (Am)', 'Jazz', 'Am → Am(maj7) → Am7 → Am6: descending inner voice.',
    ['The 5th of Am walks down A–G#–G–F# while everything else holds — the "James Bond" spy-noir sound.', 'It\'s one chord with a moving line, not four separate chords.'],
    progSpec('Recipe: Minor line cliché', 4, [min(57), [57, 60, 64, 68], min7(57), m6(57)])),
  R('jazz-tritone-sub', 'Tritone sub ii–bII7–I (C)', 'Jazz', 'Dm7 → Db7 → Cmaj7: the flat-two dominant.',
    ['The Db7 replaces G7 — same tritone (F–B/Cb), but the bass slides chromatically Db→C for a silky resolution.', 'The reharm move that instantly makes a cadence sound "jazzier".'],
    progSpec('Recipe: Tritone sub (C)', 4, [min7(62), dom7(61), maj7(60)])),
  R('jazz-backdoor', 'Backdoor ii–bVII7–I (C)', 'Jazz', 'Fm7 → Bb7 → Cmaj7: the subdominant-minor backdoor.',
    ['The bVII7 (Bb7) resolves to I from below — the "backdoor" cadence, warmer and more surprising than a straight V.', 'Borrowed from the parallel minor; a Steely Dan / gospel favourite.'],
    progSpec('Recipe: Backdoor (C)', 4, [min7(65), dom7(58), maj7(60)])),

  // ── LOFI / NEO-SOUL ────────────────────────────────────────────────────────
  R('lofi-imaj7-iv-iii-vi', 'Lofi Imaj7–IVmaj7–iii7–vi7 (C)', 'Lofi', 'Cmaj7 → Fmaj7 → Em7 → Am7: mellow study loop.',
    ['All 7th chords = that soft, hazy lofi texture where nothing is sharp or urgent.', 'The stepwise iii→vi keeps it drifting; loop it under a dusty drum break.'],
    progSpec('Recipe: Lofi maj7 loop', 4, [maj7(60), maj7(65), min7(64), min7(57)])),
  R('lofi-ii-v-imaj7-vi', 'Lofi ii7–V7–Imaj7–vi7 (C)', 'Lofi', 'Dm7 → G7 → Cmaj7 → Am7: jazzy resolve then float.',
    ['A gentle ii–V resolving to Imaj7, then vi7 to keep the loop open and unresolved.', 'The vi7 at the end is what makes it want to go round again.'],
    progSpec('Recipe: Lofi ii–V loop', 4, [min7(62), dom7(55), maj7(60), min7(57)])),
  R('neosoul-imaj9-iv9', 'Neo-soul Imaj9–IV9 (Eb)', 'Neo-Soul', 'Ebmaj9 → Ab9: lush D\'Angelo-style two-chord groove.',
    ['Extended 9th chords and a slow harmonic rhythm — the whole vibe is in the voicing, not the changes.', 'Sit on each chord for bars and let a bass and Rhodes breathe.'],
    progSpec('Recipe: Neo-soul 9ths', 8, [[63, 67, 70, 74, 77], [56, 60, 63, 68]])),
  R('neosoul-iv-iii-vi-ii', 'Neo-soul IVmaj7–iii7–vi7–ii7 (C)', 'Neo-Soul', 'Fmaj7 → Em7 → Am7 → Dm7: descending 7ths.',
    ['A smooth stepwise descent through the diatonic 7ths — warm, churchy, endlessly loopable.', 'Add a chromatic passing bass between roots for the classic neo-soul slide.'],
    progSpec('Recipe: Neo-soul descent', 4, [maj7(65), min7(64), min7(57), min7(62)])),
  R('lofi-minor-i-iv7-VI-V', 'Lofi minor i7–iv7–VImaj7–V7 (A minor)', 'Lofi', 'Am7 → Dm7 → Fmaj7 → E7: rainy-night loop.',
    ['Minor-key lofi: the harmonic-minor V (E7) gives a bittersweet pull back to Am7.', 'The Fmaj7 (VI) is the warm shoulder before the tension returns.'],
    progSpec('Recipe: Lofi minor loop', 4, [min7(57), min7(62), maj7(53), dom7(52)])),
  R('lofi-chromatic-turn', 'Lofi chromatic turnaround (C)', 'Lofi', 'Cmaj7 → C#dim7 → Dm7 → G7: passing diminished.',
    ['The C#dim7 is a chromatic passing chord bridging I and ii — that little slip is pure lofi/jazz sweetness.', 'Keep the bass moving C–C#–D–G for a walking feel.'],
    progSpec('Recipe: Lofi chromatic turn', 4, [maj7(60), dim7(61), min7(62), dom7(55)])),

  // ── HOUSE / EDM / TRANCE ───────────────────────────────────────────────────
  R('house-i-iii-vi-iv-min', 'Deep house i–III–VI–iv (A minor)', 'House', 'Am → C → F → Dm: warm minor rotation.',
    ['Minor but not sad — the III (C) and VI (F) keep it soulful, perfect for a Rhodes-y deep-house pad.', 'Loop it under a four-floor kick and it drives itself.'],
    progSpec('Recipe: Deep house (Am)', 4, [min(57), maj(60), maj(65), min(62)])),
  R('house-i-v-vi-iv-min7', 'House i7–v7–VI–VII (A minor)', 'House', 'Am7 → Em7 → Fmaj7 → G: uplifting minor climb.',
    ['The VII (G) at the top lifts the loop back up — classic vocal-house optimism inside a minor key.', 'The 7ths keep the pads lush behind the beat.'],
    progSpec('Recipe: House climb (Am)', 4, [min7(57), min7(52), maj7(53), maj(55)])),
  R('trance-i-vi-iii-vii', 'Trance i–VI–III–VII (A minor)', 'Trance', 'Am → F → C → G: the euphoric anthem loop.',
    ['The most-used trance progression — a minor start that keeps resolving upward, built for the breakdown-to-drop lift.', 'Layer supersaws on each chord and it writes the anthem itself.'],
    progSpec('Recipe: Trance anthem (Am)', 4, [min(57), maj(65), maj(60), maj(55)])),
  R('trance-i-vii-vi-vii', 'Trance i–VII–VI–VII (E minor)', 'Trance', 'Em → D → C → D: hypnotic three-chord rock-up.',
    ['Only three chords, endlessly rocking — the repeated VII (D) is the tension that never quite releases.', 'Perfect under a rolling 16th-note bassline.'],
    progSpec('Recipe: Trance rock-up (Em)', 4, [min(52), maj(50), maj(60), maj(50)])),
  R('edm-festival-vi-iv-i-v', 'Festival vi–IV–I–V (C)', 'EDM', 'Am → F → C → G: the big-room drop loop.',
    ['The axis rotated to start on vi — hits hard because the drop lands on the emotional minor first.', 'Sidechain a saw stack to the kick and it\'s a main-stage drop.'],
    progSpec('Recipe: Festival drop (C)', 4, [min(69), maj(65), maj(60), maj(67)])),
  R('edm-future-bass-IV-V-iii-vi', 'Future bass IVmaj7–V–iii–vi (C)', 'EDM', 'Fmaj7 → G → Em → Am: the royal road, EDM-ified.',
    ['The royal road progression is the backbone of future bass — the iii→vi turn under a pitched vocal chop is the whole genre.', 'Add 9ths to the F and G for that glossy detuned-supersaw sheen.'],
    progSpec('Recipe: Future bass (C)', 4, [maj7(65), maj(67), min(64), min(69)])),
  R('house-piano-i-iv-ii-v', 'Piano house I–IV–ii–V (C)', 'House', 'C → F → Dm → G: bright 90s piano loop.',
    ['The classic uplifting piano-house rotation — major, hopeful, made for stabbed chords on the offbeat.', 'Play it as short staccato stabs and it becomes instant 90s rave.'],
    progSpec('Recipe: Piano house (C)', 4, [maj(60), maj(65), min(62), maj(67)])),
  R('techno-drone-i-bii', 'Techno drone i–bII (A minor)', 'Techno', 'Am → Bbmaj: dark Phrygian semitone pull.',
    ['Just two chords a semitone apart — the bII (Bb) is the Phrygian colour that makes techno feel ominous.', 'Hold each for many bars; the tension is in the drone, not the change.'],
    progSpec('Recipe: Techno drone', 8, [min(57), maj(58)])),

  // ── R&B / FUNK / GOSPEL ────────────────────────────────────────────────────
  R('funk-i7-iv7', 'Funk I7–IV7 (E)', 'Funk', 'E9 → A9: the one-chord-ish funk vamp.',
    ['Funk lives on dominant 9th chords and a tight groove — harmony barely moves so the rhythm can do everything.', 'Sit on E9, hit A9 for the change, and let the guitar scratch the 16ths.'],
    progSpec('Recipe: Funk vamp (E)', 8, [[52, 56, 59, 62, 66], [57, 61, 64, 67, 71]])),
  R('funk-ii-v-vamp', 'Funk ii7–V7 vamp (C)', 'Funk', 'Dm7 → G7: two-chord James Brown pocket.',
    ['A ii–V that never resolves — it just cycles, keeping everything suspended for the groove.', 'The unresolved tension is why it feels like it could go forever.'],
    progSpec('Recipe: Funk ii–V vamp', 4, [min7(62), dom7(55)])),
  R('gospel-i-iii-iv-iv', 'Gospel I–III7–IV–iv (C)', 'Gospel', 'C → E7 → F → Fm: the "amen" with a secondary dominant.',
    ['The E7 (III7) is a secondary dominant pulling to vi/IV, and the IV→iv (F→Fm) is the classic gospel darkening before home.', 'That major-to-minor IV move is pure church.'],
    progSpec('Recipe: Gospel move (C)', 4, [maj(60), dom7(64), maj(65), min(65)])),
  R('gospel-251-chain', 'Gospel 6–2–5–1 (C)', 'Gospel', 'A7 → D7 → G7 → C: all-dominant cycle of fifths.',
    ['Making every chord a dominant 7 (A7–D7–G7–C) is the gospel/ragtime "ride" — each one pulls hard to the next.', 'Add a walking bass down the fifths and it swings itself to church.'],
    progSpec('Recipe: Gospel 6–2–5–1', 4, [dom7(57), dom7(50), dom7(55), maj(60)])),
  R('rnb-imaj7-iiim7-vim7-iim7', 'R&B Imaj7–iii7–vi7–ii7 (C)', 'R&B', 'Cmaj7 → Em7 → Am7 → Dm7: silky descent to a ii.',
    ['Smooth quiet-storm harmony — the descending 7ths glide, ending on ii7 to keep it wanting more.', 'Perfect for a slow-jam Rhodes bed under a breathy vocal.'],
    progSpec('Recipe: R&B descent', 4, [maj7(60), min7(64), min7(57), min7(62)])),
  R('rnb-iv-v-iii-vi', 'R&B IV–V–iii–vi (C)', 'R&B', 'Fmaj7 → G7 → Em7 → Am7: soulful royal road.',
    ['The royal road with jazz 7ths — the IV–V build resolving to the deceptive vi is peak 90s/2000s R&B.', 'Slow it down and it becomes a wedding-song staple.'],
    progSpec('Recipe: R&B royal road', 4, [maj7(65), dom7(55), min7(64), min7(57)])),
  R('funk-minor-i7-iv7-v7', 'Minor funk i7–iv7–V7 (A minor)', 'Funk', 'Am7 → Dm7 → E7: greasy minor blues-funk.',
    ['A minor i–iv with a dominant V7 for grit — the E7 gives it that snapping resolution back to Am7.', 'Think Meters / New Orleans minor-key funk.'],
    progSpec('Recipe: Minor funk (Am)', 4, [min7(57), min7(62), dom7(52)])),

  // ── BLUES ──────────────────────────────────────────────────────────────────
  R('blues-12bar-a', '12-bar blues (A)', 'Blues', 'A7 → D7 → A7 → E7: the fundamental blues form.',
    ['The universal blues frame condensed to its four functional chords — I7, IV7, V7 all dominant, all gritty.', 'Expand to the full 12 bars: I I I I / IV IV I I / V IV I V.'],
    progSpec('Recipe: 12-bar (A)', 4, [dom7(57), dom7(50), dom7(57), dom7(52)])),
  R('blues-quick-change', 'Quick-change blues (C)', 'Blues', 'C7 → F7 → C7 → C7: the IV in bar 2.',
    ['The "quick change" hits IV7 in bar 2 instead of waiting — a small variation that instantly sounds more sophisticated.', 'A staple of Chicago and Texas blues.'],
    progSpec('Recipe: Quick-change (C)', 4, [dom7(60), dom7(53), dom7(60), dom7(60)])),
  R('blues-minor-i-iv-v', 'Minor blues i–iv–V7 (A minor)', 'Blues', 'Am7 → Dm7 → E7: the smoky minor blues.',
    ['Minor blues keeps i and iv minor but leaves V dominant (E7) so it still resolves hard — think "The Thrill Is Gone".', 'The contrast of minor colour with a bright V7 is the whole mood.'],
    progSpec('Recipe: Minor blues (Am)', 4, [min7(57), min7(62), dom7(52)])),
  R('blues-jazz-turn', 'Jazz-blues turnaround (F)', 'Blues', 'F7 → D7 → Gm7 → C7: the last four bars.',
    ['The classic jazz-blues turnaround — a secondary dominant (D7) sets up the ii–V home.', 'These are the four bars that loop you back to the top of the chorus.'],
    progSpec('Recipe: Jazz-blues turn (F)', 4, [dom7(53), dom7(50), min7(55), dom7(60)])),

  // ── CINEMATIC / FILM ───────────────────────────────────────────────────────
  R('cine-i-bvi-bvii', 'Epic i–bVI–bVII (E minor)', 'Cinematic', 'Em → C → D: the trailer-music climb.',
    ['The bVI→bVII rise under a minor tonic is the sound of every epic trailer build — heroic and dark at once.', 'Add a low drone on E and swelling strings for instant scale.'],
    progSpec('Recipe: Epic build (Em)', 4, [min(52), maj(60), maj(50)])),
  R('cine-i-v-vi-iv-minor', 'Cinematic i–bIII–bVII–iv (A minor)', 'Cinematic', 'Am → C → G → Dm: sweeping minor journey.',
    ['A wandering minor loop with no strong cadence — it feels like travel, distance, longing.', 'Great under a solo instrument (cello, horn) carrying the melody.'],
    progSpec('Recipe: Cinematic journey (Am)', 4, [min(57), maj(60), maj(55), min(62)])),
  R('cine-picardy', 'Picardy-third resolve (A minor→A major)', 'Cinematic', 'Am → Dm → E → A: the dark loop that ends bright.',
    ['A minor progression that resolves onto a MAJOR tonic (A) — the "Picardy third", a Baroque trick for a hopeful ending.', 'That final major chord after all the minor is the emotional payoff.'],
    progSpec('Recipe: Picardy resolve', 4, [min(57), min(62), maj(52), maj(57)])),
  R('cine-lydian-i-ii', 'Lydian I–II (C)', 'Cinematic', 'C → D: the wonder / space-and-magic sound.',
    ['A major II chord (D major) over a C tonic gives the raised 4th (F#) — the Lydian mode, the sound of awe and the fantastical.', 'John Williams and Pixar live here; hold both chords and float.'],
    progSpec('Recipe: Lydian wonder', 8, [maj(60), maj(62)])),
  R('cine-chromatic-mediant', 'Chromatic mediant I–bVI (C→Ab)', 'Cinematic', 'C → Ab: the "hero shift" chord change.',
    ['Two major chords a third apart with no key relationship — the jarring, glorious shift used for reveals and transformations.', 'It sounds impossible and right at the same time; that\'s the magic.'],
    progSpec('Recipe: Chromatic mediant', 4, [maj(60), maj(56)])),
  R('cine-ostinato-min', 'Tension ostinato i–bII–i–VII (E minor)', 'Cinematic', 'Em → F → Em → D: Phrygian dread.',
    ['The bII (F) against E minor is Phrygian — the sound of menace, siege, oncoming threat.', 'Keep it low and repetitive; the horror is in the repetition.'],
    progSpec('Recipe: Phrygian dread', 4, [min(52), maj(53), min(52), maj(50)])),

  // ── AMBIENT ────────────────────────────────────────────────────────────────
  R('ambient-imaj7-iiimin7', 'Ambient Imaj7–iii7 drift (C)', 'Ambient', 'Cmaj7 → Em7: two chords, endless space.',
    ['Two closely-related 7th chords held for ages — the shared tones mean the change is barely perceptible, just a colour shift.', 'Reverb-drenched and slow; the harmony is a texture, not a progression.'],
    progSpec('Recipe: Ambient drift', 8, [maj7(60), min7(64)])),
  R('ambient-sus-float', 'Ambient sus2 float (D)', 'Ambient', 'Dsus2 → Gsus2: open, resolution-free stillness.',
    ['Suspended chords have no 3rd, so they never commit to major or minor — pure openness, ideal for ambient beds.', 'Layer them with a soft pad and long attack.'],
    progSpec('Recipe: Ambient sus float', 8, [sus2(50), sus2(55)])),
  R('ambient-modal-min7', 'Ambient Aeolian i7–VI (A minor)', 'Ambient', 'Am7 → Fmaj7: gentle minor wash.',
    ['A slow i–VI in minor with 7ths — melancholy but peaceful, the sound of grey-morning ambient.', 'No V, no tension; it just breathes.'],
    progSpec('Recipe: Ambient Aeolian', 8, [min7(57), maj7(53)])),

  // ── FOLK / COUNTRY ─────────────────────────────────────────────────────────
  R('folk-i-iv-v-country', 'Country I–IV–I–V–I (G)', 'Country', 'G → C → G → D → G: the campfire frame.',
    ['The three-chord country/folk bedrock — I, IV, V, everything sung around them.', 'Add a bass run between chords (G–A–B–C) for the country walk-up.'],
    progSpec('Recipe: Country I–IV–V (G)', 4, [maj(55), maj(60), maj(55), maj(50), maj(55)])),
  R('folk-i-v-vi-iv-fingerpick', 'Folk I–V–vi–IV fingerstyle (D)', 'Folk', 'D → A → Bm → G: the singer-songwriter axis.',
    ['The axis progression in a guitar-friendly key with open strings — the sound of a hundred coffee-house sets.', 'Fingerpick it slow for a wistful, intimate feel.'],
    progSpec('Recipe: Folk axis (D)', 4, [maj(50), maj(57), min(59), maj(55)])),
  R('folk-modal-i-bvii-iv', 'Folk-rock I–bVII–IV (G)', 'Folk', 'G → F → C: the Mixolydian jangle.',
    ['The bVII (F) gives that modal, timeless folk-rock sound — no leading tone, just open ringing chords.', 'Think 60s jangle-pop and Laurel Canyon.'],
    progSpec('Recipe: Folk-rock (G)', 4, [maj(55), maj(53), maj(60)])),
  R('country-i-vi-iv-v-shuffle', 'Country I–vi–IV–V (C)', 'Country', 'C → Am → F → G: the two-step / doo-wop country.',
    ['The 50s changes with a country shuffle — sweet, sentimental, and made for close harmony.', 'A telecaster and a fiddle finish the picture.'],
    progSpec('Recipe: Country I–vi–IV–V', 4, [maj(60), min(69), maj(65), maj(67)])),

  // ── LATIN / BOSSA ──────────────────────────────────────────────────────────
  R('latin-montuno-ii-v', 'Salsa montuno ii–V (C)', 'Latin', 'Dm7 → G7: the piano-montuno two-chord vamp.',
    ['Salsa piano rides a repeating ii–V vamp with a syncopated montuno pattern over the clave.', 'Harmony is minimal so the rhythm and clave lead.'],
    progSpec('Recipe: Salsa montuno', 4, [min7(62), dom7(55)])),
  R('bossa-i-ii-v-vi', 'Bossa Imaj7–ii7–V7–vi7 (C)', 'Latin', 'Cmaj7 → Dm7 → G7 → Am7: sunlit Jobim loop.',
    ['Warm maj7/min7 voicings with a gentle ii–V — the relaxed, sophisticated core of bossa nova.', 'Play it soft with a nylon guitar and a light clave.'],
    progSpec('Recipe: Bossa loop', 4, [maj7(60), min7(62), dom7(55), min7(57)])),
  R('latin-andalusian', 'Andalusian i–VII–VI–V (A minor)', 'Latin', 'Am → G → F → E: the flamenco/Spanish cadence.',
    ['The descending Phrygian-flavoured line with a MAJOR V (E) — the sound of flamenco and Spanish guitar.', 'That E major over an A-minor world is the fiery Phrygian-dominant colour.'],
    progSpec('Recipe: Andalusian (Am)', 4, [min(57), maj(55), maj(65), maj(52)])),
  R('latin-tango-i-iv-v-i', 'Tango i–iv–V7–i (D minor)', 'Latin', 'Dm → Gm → A7 → Dm: dramatic minor tango.',
    ['A tight minor i–iv–V with a hard dominant resolution — the theatrical push-pull of tango.', 'Stab the chords on the beat and let the bandoneón sing between.'],
    progSpec('Recipe: Tango (Dm)', 4, [min(50), min(55), dom7(57), min(50)])),

  // ── SYNTHWAVE ──────────────────────────────────────────────────────────────
  R('synthwave-i-vi-iv-v', 'Synthwave i–VI–III–VII (D minor)', 'Synthwave', 'Dm → Bb → F → C: neon-night nostalgia.',
    ['The minor anthem loop with 80s gloss — arpeggiate it on a saw synth for instant Outrun.', 'The all-diatonic climb keeps it driving and wistful.'],
    progSpec('Recipe: Synthwave (Dm)', 4, [min(50), maj(58), maj(53), maj(60)])),
  R('synthwave-i-bvii-vi', 'Synthwave i–bVII–bVI (A minor)', 'Synthwave', 'Am → G → F: the descending retro-drive.',
    ['A stepwise Aeolian descent — the propulsive, slightly melancholy pulse under 80s chase scenes.', 'Put it under a gated-reverb drum and a fat bass arp.'],
    progSpec('Recipe: Synthwave descent', 4, [min(57), maj(55), maj(65)])),
  R('synthwave-maj-i-v-vi-iii', 'Retro-pop I–V–vi–iii (A)', 'Synthwave', 'A → E → F#m → C#m: bright 80s pop-gloss.',
    ['Major and shiny with the iii for a touch of longing — the sound of 80s prom-pop.', 'DX7 electric piano and a big snare complete it.'],
    progSpec('Recipe: Retro-pop (A)', 4, [maj(57), maj(52), min(54), min(49)])),

  // ── METAL ──────────────────────────────────────────────────────────────────
  R('metal-i-bii-phrygian', 'Metal Phrygian i–bII (E)', 'Metal', 'E5 → F5: the dark drop-tuned menace.',
    ['The bII (F) against an E root is Phrygian — the heaviest, most ominous move in metal.', 'Palm-mute the root and stab the bII; the semitone is the whole threat.'],
    progSpec('Recipe: Metal Phrygian (E)', 4, [maj(52), maj(53)])),
  R('metal-i-bvi-bvii', 'Metal i–bVI–bVII (E minor)', 'Metal', 'Em → C → D: the anthemic gallop climb.',
    ['The Aeolian climb played with gain and a galloping palm-mute — Iron Maiden\'s bread and butter.', 'The bVI→bVII rise is triumphant even at full aggression.'],
    progSpec('Recipe: Metal gallop (Em)', 4, [min(52), maj(60), maj(50)])),
  R('metal-chromatic-i-biii-iv', 'Metal i–biii–iv chromatic (E)', 'Metal', 'Em → G → Am: dark chromatic weight.',
    ['A heavy minor climb with a biii for extra darkness — droptuned and doomy.', 'Slow it down for doom, speed it up for thrash.'],
    progSpec('Recipe: Metal chromatic (Em)', 4, [min(52), maj(55), min(57)])),

  // ── CLASSICAL / BAROQUE ────────────────────────────────────────────────────
  R('classical-i-iv-v-i', 'Perfect cadence I–IV–V–I (C)', 'Classical', 'C → F → G → C: the textbook authentic cadence.',
    ['The foundation of common-practice harmony — subdominant, dominant, tonic — the V→I is the "period" at the end of a musical sentence.', 'Everything in classical form is an elaboration of this arc.'],
    progSpec('Recipe: Perfect cadence (C)', 4, [maj(60), maj(65), maj(67), maj(60)])),
  R('classical-circle-of-fifths', 'Circle-of-fifths sequence (C)', 'Classical', 'Am → Dm → G → C: the descending-fifths chain.',
    ['Roots falling by fifths (A–D–G–C) — the strongest, most inevitable harmonic motion in tonal music.', 'Baroque composers spun entire sequences out of this cycle.'],
    progSpec('Recipe: Circle of fifths (C)', 4, [min(57), min(62), maj(55), maj(60)])),
  R('classical-lament-bass', 'Lament bass (descending tetrachord, A minor)', 'Classical', 'Am → G → F → E: the ground-bass of grief.',
    ['The bass falls A–G–F–E (a minor tetrachord) — the "lament" ground under Purcell\'s Dido and countless laments.', 'The inexorable stepwise fall is the sound of sorrow itself.'],
    progSpec('Recipe: Lament bass (Am)', 4, [min(57), maj(55), maj(65), maj(52)])),
  R('classical-deceptive', 'Deceptive cadence V–vi (C)', 'Classical', 'G → Am: the resolution that isn\'t.',
    ['V "should" go to I, but resolving to vi (Am) instead is the deceptive cadence — a surprise that prolongs the music.', 'Composers use it to dodge the ending and keep a phrase spinning.'],
    progSpec('Recipe: Deceptive cadence', 4, [maj(67), min(57)])),
  R('classical-plagal', 'Plagal "amen" IV–I (C)', 'Classical', 'F → C: the church cadence.',
    ['IV→I is the soft "amen" resolution — no leading-tone urgency, just a gentle settling home.', 'Ubiquitous at the end of hymns.'],
    progSpec('Recipe: Plagal (C)', 4, [maj(65), maj(60)])),
  R('classical-neapolitan', 'Neapolitan bII6–V–i (A minor)', 'Classical', 'Bb → E → Am: the dramatic flat-two.',
    ['The Neapolitan (bII, here Bb major) is a lush chromatic predominant that heightens the pull into V–i.', 'A favourite of Beethoven for a sudden dark intensity before the cadence.'],
    progSpec('Recipe: Neapolitan (Am)', 4, [maj(58), maj(52), min(57)])),

  // ── EXTRA BASS GROUNDS ─────────────────────────────────────────────────────
  R('bass-house-octave', 'House octave bassline (A minor)', 'House', 'A–A(oct)–A–A: the pumping octave root.',
    ['The relentless octave-jump bass under four-floor house — root down, root up, all groove.', 'Sidechain it to the kick for the classic pump.'],
    bassSpec('Recipe: House octave bass', 1, [45, 57, 45, 57, 45, 57, 45, 57])),
  R('bass-walking-jazz', 'Walking bass over ii–V–I (C)', 'Jazz', 'D–F–G–B–C–E–G–A: a swung walk home.',
    ['A quarter-note walking line outlining Dm7–G7–Cmaj7 — chord tones on the beat, passing tones between.', 'The engine of swing; the bass alone implies the whole progression.'],
    bassSpec('Recipe: Walking bass (C)', 1, [50, 53, 55, 59, 60, 64, 55, 57])),
  R('bass-reggae-drop', 'Reggae bass drop (A minor)', 'Reggae', 'A–.–E–.–D–.–A: the space-heavy root line.',
    ['Reggae bass is as much about the rests as the notes — deep roots landing on the off-beats, leaving air for the skank.', 'Round, dubby, and patient.'],
    bassSpec('Recipe: Reggae bass', 2, [45, 40, 38, 45])),
  R('bass-synth-arp-min', 'Synthwave bass arp (D minor)', 'Synthwave', 'D–D–A–D–F–D–A–D: driving 16th arp.',
    ['A rolling 16th-note root-fifth-octave arp — the propulsive pulse under synthwave and Italo.', 'Run it through a resonant filter with movement for the retro drive.'],
    bassSpec('Recipe: Synth bass arp', 1, [50, 50, 57, 50, 53, 50, 57, 50])),

  // ── FINAL BATCH (to 100+) ──────────────────────────────────────────────────
  R('pop-i-v-vi-iv-half', 'Half-time axis I–V–vi–IV (G)', 'Pop', 'G → D → Em → C: the axis in a warm guitar key.',
    ['Same four chords, transposed to G where open strings ring — the singer-songwriter default.', 'Two bars per chord for a spacious ballad feel.'],
    progSpec('Recipe: Axis (G)', 4, [maj(55), maj(50), min(52), maj(60)])),
  R('pop-emotional-iv-v-vi', 'Emotional IV–V–vi (C)', 'Pop', 'F → G → Am: the pre-chorus that lands soft.',
    ['A three-chord build that resolves deceptively to vi — the swell before a big minor-key hook.', 'The IV→V rise raises the stakes; vi undercuts them beautifully.'],
    progSpec('Recipe: IV–V–vi (C)', 4, [maj(65), maj(67), min(69)])),
  R('jazz-ii-v-i-vi-full', 'Full turnaround ii–V–I–vi (C)', 'Jazz', 'Dm7 → G7 → Cmaj7 → A7: resolve then reload.',
    ['Resolves to I then pivots on a secondary dominant (A7) that pulls back to ii — a self-perpetuating loop.', 'The A7 (V/ii) is the little kick that restarts the cycle.'],
    progSpec('Recipe: ii–V–I–VI7 (C)', 4, [min7(62), dom7(55), maj7(60), dom7(57)])),
  R('jazz-modal-phrygian', 'Modal Phrygian vamp (E)', 'Jazz', 'Em7 → Fmaj7: the flamenco-jazz brooder.',
    ['E Phrygian — the bII (F) next to the i chord gives a Spanish, unsettled modal colour.', 'Improvise E Phrygian over the two chords; never resolve.'],
    progSpec('Recipe: Phrygian vamp (E)', 8, [min7(52), maj7(53)])),
  R('disco-i-vi-ii-v-seventh', 'Disco Imaj7–vi7–ii7–V7 (C)', 'Disco', 'Cmaj7 → Am7 → Dm7 → G7: the four-on-floor turnaround.',
    ['The rhythm-changes turnaround with lush 7ths and a driving four-floor kick — the Chic/Nile Rodgers sound.', 'Scratchy 16th guitar and an octave bass finish it.'],
    progSpec('Recipe: Disco turnaround', 4, [maj7(60), min7(57), min7(62), dom7(55)])),
  R('worship-i-v-vi-iv-add9', 'Worship I–V–vi–IV with sus (G)', 'Worship', 'Gsus → D → Em7 → Csus2: the modern-hymn wash.',
    ['The axis dressed in sus and add chords — that open, unresolved shimmer of contemporary worship.', 'Delay-soaked electric and a swelling pad carry it.'],
    progSpec('Recipe: Worship axis (G)', 4, [sus4(55), maj(50), min7(52), sus2(60)])),
  R('trap-min-i-VI-III-VII', 'Trap i–VI–III–VII (F# minor feel)', 'Trap', 'F#m → D → A → E: the dark melodic-trap loop.',
    ['The minor anthem loop under 808s — melodic trap borrows the same emotional climb as trance.', 'Space the chords wide and let the 808 glide between roots.'],
    progSpec('Recipe: Trap minor loop', 4, [min(54), maj(50), maj(57), maj(52)])),
  R('drill-min-i-iv-v', 'Drill i–iv–VII (D minor)', 'Drill', 'Dm → Gm → C: the dark sliding-808 frame.',
    ['A stark minor i–iv with a bVII — sparse harmony leaving room for the sliding drill 808 and hi-hat triplets.', 'Keep it minimal; the menace is in the space.'],
    progSpec('Recipe: Drill frame (Dm)', 4, [min(50), min(55), maj(60)])),
  R('world-hijaz', 'Hijaz cadence (Phrygian dominant, D)', 'World', 'D(maj3,b2) → Eb → D: Middle-Eastern colour.',
    ['Phrygian dominant — a major 3rd over a b2 scale — the exotic, mysterious sound of Hijaz maqam and klezmer.', 'The augmented-second gap in the scale is the signature; drone the D underneath.'],
    progSpec('Recipe: Hijaz cadence', 4, [maj(50), maj(51), maj(50)])),
  R('world-celtic-i-bvii-iv-i', 'Celtic I–bVII–IV–I (D)', 'World', 'D → C → G → D: the Mixolydian jig frame.',
    ['The bVII (C) gives the old modal, folk-dance character behind reels and jigs.', 'Set it to a 6/8 lilt and it dances itself.'],
    progSpec('Recipe: Celtic (D)', 4, [maj(50), maj(60), maj(55), maj(50)])),
  R('rnb-neosoul-imaj9-vi9', 'Quiet-storm Imaj9–vi9 (F)', 'R&B', 'Fmaj9 → Dm9: two lush chords, all mood.',
    ['Extended 9th voicings on a slow I–vi — the whole vibe is in the richness of the chords, not the motion.', 'Rhodes, brushed drums, and a fretless bass.'],
    progSpec('Recipe: Quiet storm', 8, [[53, 57, 60, 64, 67], [50, 53, 57, 60, 64]])),
  R('cine-hopeful-i-iii-IV', 'Hopeful I–iii–IV–I (C)', 'Cinematic', 'C → Em → F → C: the sunrise resolve.',
    ['A gentle major loop that keeps returning home — the sound of resolution, dawn, quiet triumph.', 'Strings swelling on IV then settling to I is the emotional exhale.'],
    progSpec('Recipe: Hopeful resolve (C)', 4, [maj(60), min(64), maj(65), maj(60)])),
  R('pop-doo-wop-full-seventh', 'Doo-wop 7ths I–vi–IV–V (C)', 'Pop', 'Cmaj7 → Am7 → Fmaj7 → G7: the 50s with jazz colour.',
    ['The 50s changes voiced with 7ths — sweeter, more sophisticated, the sound of Beach Boys harmony.', 'Stack close vocal harmonies on top and it glows.'],
    progSpec('Recipe: Doo-wop 7ths', 4, [maj7(60), min7(57), maj7(65), dom7(55)])),
  R('house-organ-ii-v-i-vi', 'Soulful house ii–V–I–vi (C)', 'House', 'Dm7 → G7 → Cmaj7 → Am7: the deep-house Rhodes loop.',
    ['A jazzy ii–V–I with a vi tail — the soulful, garage-house chord bed under a diva vocal.', 'Play it on a warm organ/Rhodes with a filtered pad.'],
    progSpec('Recipe: Soulful house', 4, [min7(62), dom7(55), maj7(60), min7(57)])),
]
